### PR TITLE
wip: update to bitcoin 0.30.0

### PR DESCRIPTION
**Pull request by dpc**
Currently blocked on 

- [ ] https://github.com/ElementsProject/lightning/issues/6349
- [x] https://github.com/bitcoindevkit/rust-esplora-client/pull/51
- [ ] possibly something else?

### CODE REVIEW

**Comment by dpc** [comment]
Still blocked.

**Comment by m1sterc001guy** [comment]
Also blocked on https://github.com/lightningdevkit/rust-lightning/issues/2124

**Comment by dpc** [comment]
Is this still on anyone's radar?

@tvolk131 I remember you PR about miniscript. Is this still useful for you or anyone?

**Comment by tvolk131** [comment]
It's on my radar but I've been busy working on LDK gateway integration and haven't been prioritizing this as of late. Yep, #4086 migrated most of the codebase to miniscript v10. Upgrading to bitcoin v30 requires such wide-sweeping changes that we'll almost certainly want to do it incrementally. That's why I added `bitcoin_migration.rs` in that PR. I think we can close this PR out, although maybe it'd be worth getting a second opinion from @m1sterc001guy.

**Pull request closed without merging**
