### PR TITLE
refactor(gateway): make `gateway-cli ` commands names similar to `fedimint-cli`

### LINKED ISSUE #1561: Unify `gateway-cli` and `fedimint-cli` commands
These two should behave generally very similarly.

* `connect-fed` vs `join-federation,`
* `--work-dir` vs federationid (positional, meh)
* `connect-info` vs `info`
* lot of other commands

### PR DESCRIPTION
**Pull request by 15IITian**
fix #1561

### CODE REVIEW

**Comment by justinmoon** [comment]
@bradleystachurski will this break backwards compatibility tests?

**Review by bradleystachurski — COMMENTED** [review]
> will this break backwards compatibility tests?

Yep, this breaks compatibility with the CLI. It's still an open question what our philosophy is for CLI stability, but I think we should avoid incompatible changes unless there's a material benefit.

> Should we adapt the test script instead here? At least in my mind we didn't commit to CLI stability (maybe we should? @justinmoon)

https://github.com/fedimint/fedimint/issues/4016#issuecomment-1893662992

For visibility, this is the failure from CI

```
00:01:12     0: command: gateway-cli --rpcpassword=theresnosecondbest -a http://127.0.0.1:19421/v1 connect-fed fed11qgqpw9thwvaz7te3xgmjuvpwxqhrzw33xgurxd30qqqjqsljxgwp2q73rzk58n0jzdw04fvlduekzdnfuuaxcnvj5n4zfajpydcezc
00:01:12     1: exit status: 2
00:01:12        stdout:
00:01:12        
00:01:12        stderr:
00:01:12        error: unrecognized subcommand 'connect-fed'
00:01:12        
00:01:12        Usage: gateway-cli [OPTIONS] <COMMAND>
00:01:12        
00:01:12        For more information, try '--help'.
```

https://github.com/fedimint/fedimint/actions/runs/7728708478/job/21070150985?pr=4187#step:5:4878

If CI was able to progress, we'd also bump into issues with `address` changing to `deposit-address`.

**Comment by bradleystachurski** [comment]
> I think we should avoid incompatible changes unless there's a material benefit.

As a followup, I don't have a strong opinion on unifying these names with `fedimint-cli`. If we think it's worth introducing a breaking change we can handle versions specifically in devimint similar to https://github.com/fedimint/fedimint/blob/3a020c09a01046e6d6c0c98d8e77a67fa3425d02/devimint/src/main.rs#L454

**Comment by 15IITian** [comment]
@bradleystachurski 
I hope this  question isn't  silly   ,I am curious if there is a way to anticipate potential risk of backward incompatibility test to fail before making any changes?

**Comment by elsirion** [comment]
> I hope this question isn't silly ,I am curious if there is a way to anticipate potential risk of backward incompatibility test to fail before making any changes?

Not a silly Q, but you'd need to know our test suite for that. In general changing APIs (CLI parsing, RPCs, …) should always break our test suite, otherwise we are missing test coverage. Now that we want to provide more compatibility guarantees this makes certain minor renames rather unattractive or at least a lot of work.

**Comment by bradleystachurski** [comment]
Yep, I agree with what Eric said. Also, if you're curious if your changes break backwards-compatibility prior to opening a PR, you can run the tests locally with

```
./scripts/tests/backwards-compatibility-test.sh
```

**Comment by 15IITian** [comment]
> ./scripts/tests/backwards-compatibility-test.sh

Thanks for it.

**Comment by justinmoon** [comment]
No progress in 3 weeks. Closing.

**Pull request closed without merging**
