### PR TITLE
[DON'T MERGE] HCPP branch CI playground

### PR DESCRIPTION
**Pull request by elsirion**

### CODE REVIEW

**Comment by elsirion** [comment]
merge conflicts prevent CI from running, closing

**Comment by dpc** [comment]
@elsirion You can enable runs for branches other than `master`. https://github.com/fedimint/fedimint/blob/0a86771d0ba293162ecae1ce91d711befd0ef6ef/.github/workflows/ci-nix.yml#L8

Also https://github.com/fedimint/fedimint/blob/master/.github/workflows/ci-nix.yml#L14 should allow you to run it manually for any branch.

**Comment by dpc** [comment]
Oh. I see that you might have tried that already. :)

**Comment by elsirion** [comment]
Yep, remembered that afterwards

**Pull request closed without merging**
