### PR TITLE
chore: cleanup imports and exports in fedimint-core and fedimint-server

### PR DESCRIPTION
**Pull request by tvolk131**

### CODE REVIEW

**Review by dpc — DISMISSED** [review]

**Comment by elsirion** [comment]
Can we somehow enforce this in CI? Otherwise such changes are close to pointless since we'll regress again over time.

**Review by elsirion — DISMISSED** [review]

**Comment by dpc** [comment]
@tvolk131 Do you want to try enforcing it with `.semgrep.yaml`?

**Comment by douglaz** [comment]
Try to enforce this using clippy. For instance, enable:
https://rust-lang.github.io/rust-clippy/master/index.html#/wildcard_imports

**Comment by joschisan** [comment]
Please hold off on merging this pr as the aleph pr introduces a ton off changes in fedimint-server and any changes may send me into rebase hell

**Comment by justinmoon** [comment]
> Please hold off on merging this pr as the aleph pr introduces a ton off changes in fedimint-server and any changes may send me into rebase hell…

I just marked this PR as draft until https://github.com/fedimint/fedimint/pull/3260 is merged

**Comment by dpc** [comment]
@tvolk131 You might want to submit a commit without `fedimint-server` changes.

**Comment by tvolk131** [comment]
> You might want to submit a commit without fedimint-server changes.

Good idea! I messed around a bit and wasn't able to find a great one-size-fits-all regex to only allow wildcard imports where we want it and not where we don't. For example, it's normal to have `use super::*;` in the test module to avoid re-importing everything that the prod code is relying on. I settled on `^use .*::\*;$` which allows for the aforementioned case since it only counts uses that start with no whitespace (which will exclude any uses in a module declared within a file). It's not perfect, but it prevents regressions on several of the fixes in this PR.

**Comment by joschisan** [comment]
Please still hold off on merging this pr as I am currently working on a big refactor of the server and this will cause rebase conflicts.

**Review by dpc — DISMISSED** [review]

**Comment by dpc** [comment]
What's the status? LGTM.

**Comment by dpc** [comment]
image

Is it ready to review and land?

**Comment by tvolk131** [comment]
> Is it ready to review and land?

@joschisan wanted to hold off on submission

> Please still hold off on merging this pr as I am currently working on a big refactor of the server and this will cause rebase conflicts.

@joschisan can you please link the PR we're waiting on so I know when I should send this out for review?

**Comment by dpc** [comment]
> @joschisan wanted to hold off on submission

AFAIK it landed a week ago or more. :D

**Review by dpc — APPROVED** [review]

**Pull request merged**
