### PR TITLE
WIP: Add buffer to outgoing framed transport writer

### PR DESCRIPTION
**Pull request by elsirion**
Highly WIP, don't mind me messing around here

### CODE REVIEW

**Comment by dpc** [comment]
Is this for perf (gathering writes) or some other reason? 

Maybe we could chat a bit about the whole peer networking at some point. I'm clueless about it, and we had a conv. with kitman about it https://discord.com/channels/990354215060795454/1052585969745936444.

**Comment by elsirion** [comment]
> Is this for perf (gathering writes) or some other reason?

Nope, not for perf at all. And after I wrote some unit tests it turned out that the `BufWriter` from `tokio` doesn't even do what I want and I implemented my own, just didn't push it yesterday after getting distracted by life. Sorry for the confusion.

My goal is to make `send` always return immediately, so that the sending messages in the IO thread never blocks:

https://github.com/fedimint/fedimint/blob/86ee3a748f758593e5bc03d1ae0cd308d6cb829d/fedimint-server/src/net/peers.rs#L394-L413

To make this send call on a framed transport non-blocking the underlying stream has to be non-blocking.

My current approach with my custom `BufWriter` is to just write to the buffer and then send as much as possible, but never block. Then there's a separate async fn that can drive forward sending out the buffer while we aren't trying to send anything in particular (can just always be selected in parallel to the other tasks).

To avoid the buffer becoming too big if the connection is dead I'm planning on implementing a check before each send operation that closes the connection and clear all buffers above a certain threshold. This will prevent peers from stalling us if they aren't reading from the socket (which is a problem we found but postponed shortly after introducing the network stack).

**Comment by dpc** [comment]
> To make this send call on a framed transport non-blocking the underlying stream has to be non-blocking.

@elsirion 

All the IO in async rust is already non-blocking.

It seems to me what you want to achieve is best done with a [timeout](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html).

**Comment by elsirion** [comment]
Sure, async io doesn't block the thread, it can still block a task. That's what I'm trying to avoid, maybe in the wrong way.

Timing out isn't what we want here. A peer can block for a few s and become responsive again. But during these few seconds we couldn't send anything to other peers. So sending should happen asynchronously.

Maybe the right way to achieve that would be having a to-be-sent message buffer in the io thread from which we constantly try to send messages over the socket. I was a bit scared of cancellation safety with this option, not sure if it could lead to half-sent messages when sending is aborted in a select that had another future resolve early (but now I doubt that's a problem).

**Comment by dpc** [comment]
> Sure, async io doesn't block the thread, it can still block a task.

It doesn't have to. One task can potentially drive multiple futures at the same time:

https://docs.rs/tokio/latest/tokio/macro.join.html#examples
https://docs.rs/tokio/latest/tokio/macro.select.html#examples
https://docs.rs/tokio/latest/tokio/task/struct.JoinSet.html#examples

I imagine when doing consensus we want to send bunch of data to all peers at the same time, so I guess `JoinSet` could do.


> Timing out isn't what we want here. A


We would map over all peers, where sending to each peer is wrapped in some deadline for the whole round. At the end we would join on all and see which one were OK, and which one timed out.

Though it occured to me now that this is how  if we were not using these IO threads at all. I'm not sure what I described is what you need.

> I was a bit scared of cancellation safety with this option, not sure if it could lead to half-sent messages when sending is aborted in a select that had another future resolve early (but now I doubt that's a problem).

Cancelation safety shouldn't be a problem with network IO. In principle the tcp connection can get abruptly terminated at any point anyway. Then dropping a future or not is a matter if `select` or `join` is being used.

**Comment by dpc** [comment]
I looked again at the code, but I'm fuzzy on the overall picture of the consensus network IO. We should talk about it tomorrow. :)

**Comment by elsirion** [comment]
This is probably the wrong approach, I'll try to implement message buffering instead.

**Pull request closed without merging**
