### PR TITLE
feat: lets break tokio rt on wasm

### PR DESCRIPTION
**Pull request by maan2003**

### CODE REVIEW

**Comment by dpc** [comment]
@maan2003 If the tokio's `block_on` fails on wasm, we should have a conditional `fedimint_core::task::block_on` and enforce using that with `semgrep`?

**Comment by maan2003** [comment]
makes sense, we may want to just avoid block_on in client code

**Comment by maan2003** [comment]
nice, finally failing

**Comment by elsirion** [comment]
#4854 is a reaction to this, right?

**Comment by maan2003** [comment]
yep

**Comment by elsirion** [comment]
Can this be closed then?

**Pull request closed without merging**
