### PR TITLE
chore: bump version to 0.4.0-alpha

### PR DESCRIPTION
**Pull request by elsirion**
Also adds missing version to metrics dependency in fedimint-server.

### CODE REVIEW

**Review by justinmoon — APPROVED** [review]

**Comment by justinmoon** [comment]
Lots of conflicts

**Comment by elsirion** [comment]
@bradleystachurski could you take a look at the failing tests please? I'm not finding the time for it :(

**Comment by elsirion** [comment]
Changing the versions should be easy with:

```bash
cargo workspaces version --exact --no-git-commit --yes --force '*' --pre-id rc custom 0.4.0-alpha
```

**Comment by bradleystachurski** [comment]
Hopefully fixed with https://github.com/fedimint/fedimint/pull/4804.

I opened a separate PR that includes the fix and version bump (https://github.com/fedimint/fedimint/pull/4805) since that seems easier than resolving merge conflicts here.

**Pull request closed without merging**
