### PR TITLE
simplification: always propose block height and feerate votes

### PR DESCRIPTION
**Pull request by joschisan**
Should fix https://github.com/fedimint/fedimint/issues/3744 as block height votes and feerate votes are proposed every session now. The broadcast ordering capacity this consumes is negligible; the filtering in the proposal was a remnant of hbbft.

### CODE REVIEW

**Review by bradleystachurski — APPROVED** [review]
Looks good!

There's a possibility that we won't propose a block height if we can't get a block count from the node, however we'll always propose a feerate in the wallet server even if we can't get a response from the node.

**Comment by dpc** [comment]
I don't get it, and therefore I'm mistrustful of it.

What am I missing?

**Review by elsirion — CHANGES_REQUESTED** [review]
This is spamming the log with warnings about uncommitted dbtx:

```
2023-11-28T17:06:29.429384Z  WARN db: DatabaseTransaction has writes and has not called commit. location=   0: <fedimint_core::db::CommitTracker as core::ops::drop::Drop>::drop
             at fedimint-core/src/db/mod.rs:1227:33
   1: core::ptr::drop_in_place<fedimint_core::db::CommitTracker>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ptr/mod.rs:497:1
   2: core::ptr::drop_in_place<fedimint_core::db::MaybeRef<fedimint_core::db::CommitTracker>>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ptr/mod.rs:497:1
   3: core::ptr::drop_in_place<fedimint_core::db::DatabaseTransaction<fedimint_core::db::Committable>>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ptr/mod.rs:497:1
   4: fedimint_server::consensus::server::ConsensusServer::process_consensus_item::{{closure}}
             at fedimint-server/src/consensus/server.rs:624:5
   5: fedimint_server::consensus::server::ConsensusServer::complete_signed_session_outcome::{{closure}}
             at fedimint-server/src/consensus/server.rs:449:35
   6: fedimint_server::consensus::server::ConsensusServer::run_session::{{closure}}
             at fedimint-server/src/consensus/server.rs:412:14
   7: fedimint_server::consensus::server::ConsensusServer::run_consensus::{{closure}}
             at fedimint-server/src/consensus/server.rs:300:45
   8: fedimint_server::consensus::server::ConsensusServer::run::{{closure}}
             at fedimint-server/src/consensus/server.rs:216:45
   9: fedimint_server::FedimintServer::run::{{closure}}
             at fedimint-server/src/lib.rs:103:56
  10: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
  11: fedimintd::fedimintd::run::{{closure}}::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/join_mod.rs:95:13
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/poll_fn.rs:56:9
  13: fedimintd::fedimintd::run::{{closure}}
             at fedimintd/src/fedimintd.rs:301:48
  14: fedimintd::fedimintd::Fedimintd::run::{{closure}}::{{closure}}::{{closure}}
             at fedimintd/src/fedimintd.rs:207:18
  15: fedimint_core::task::TaskGroup::spawn_local::{{closure}}::{{closure}}
             at fedimint-core/src/task.rs:226:23
  16: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  17: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
      tokio::runtime::task::core::Core<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  19: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
  21: std::panicking::try::do_call
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  22: __rust_try
```

This can be patched using

```patch
Index: fedimint-server/src/consensus/server.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/fedimint-server/src/consensus/server.rs b/fedimint-server/src/consensus/server.rs
--- a/fedimint-server/src/consensus/server.rs	(revision 7a5a7d05525a3b77a99ef93da654030bd42bfa9a)
+++ b/fedimint-server/src/consensus/server.rs	(date 1701191495328)
@@ -29,7 +29,7 @@
 use fedimint_core::{timing, PeerId};
 use futures::StreamExt;
 use tokio::sync::watch;
-use tracing::{debug, info, warn};
+use tracing::{debug, info, trace, warn};
 
 use crate::atomic_broadcast::data_provider::{DataProvider, UnitData};
 use crate::atomic_broadcast::finalization_handler::FinalizationHandler;
@@ -590,8 +590,20 @@
             bail!("Item was discarded before we recovered");
         }
 
-        self.process_consensus_item_with_db_transaction(&mut dbtx.to_ref_nc(), item.clone(), peer)
-            .await?;
+        match {
+            // dbtx_nc has to be dropped before deactivating uncommitted warnings to avoid
+            // lifetime issues
+            let mut dbtx_nc = dbtx.to_ref_nc();
+            self.process_consensus_item_with_db_transaction(&mut dbtx_nc, item.clone(), peer)
+                .await
+        } {
+            Ok(()) => {}
+            Err(error) => {
+                dbtx.ignore_uncommitted();
+                trace!(target: LOG_CONSENSUS, ?item, ?error, "Ignoring rejected consensus item");
+                return Err(error);
+            }
+        }
 
         dbtx.insert_entry(&AcceptedItemKey(item_index), &AcceptedItem { item, peer })
             .await;
```

**Comment by elsirion** [comment]
> I don't get it, and therefore I'm mistrustful of it.

@dpc Currently, if nothing happens, peers don't contribute anything to consensus and the status API shows they are fallen out of consensus. To fix this we make modules where it doesn't matter if they contribute more often contribute every second.

I had an alternative PR #3757 that introduced more code for little benefit. @joschisan's approach fits better into the general development trajectory of the server/consensus.

**Comment by dpc** [comment]
>  To fix this we make modules where it doesn't matter if they contribute more often contribute every second.

Why it doesn't matter? :D

Making consensus contribute all the time, even if it gets merged somewhere else down the line so it doesn't matter seems like a crude hack to me.

**Review by elsirion — APPROVED** [review]
@dpc @justinmoon thoughts?

**Comment by dpc** [comment]
> once module CIs aren't latency critical anymore (only LN still depends on it, with LN v2 this will be fixed) 

Is this generally a case? Any 3rd party module can always be written in a way where this is true?

> and just propose all their proposals all the time, reducing complexity.

It's a rather trivial complexity we are reducing here. Just saying. I have 99 things I wish were simpler in Fedimint, and this ain't one. Hopefully it will not backfire down the road. And it doesn't need to backfire by a lot to not be worth it.

> A bit I guess, ideally we could check which peers have contributed units to AlephBFT imo, 

The monitoring is an auxiliary thing to the consensus, so I wouldn't mind it having to do some extra work. Otherwise it's tail wagging the dog kind of situation.


Anyway, not a blocker for me, but I doesn't sit with me well. :D

**Comment by elsirion** [comment]
> > once module CIs aren't latency critical anymore (only LN still depends on it, with LN v2 this will be fixed)
> 
> Is this generally a case? Any 3rd party module can always be written in a way where this is true?

For me that's something to discuss with @joschisan once we get there. My main objective here is to unblock @justinmoon and @okjodom for the admin UI. I couldn't care less about this for now otherwise (eventually we want it, but not a high prion other than it affecting the UI development which is on the hot path of the release process).

The nice thing about this change is that, should we decide it's not worth it, we can just roll it back without breaking compatibility. The performance impact also shouldn't be noticeable (this should consume far less than 5% of consensus capacity).

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.2`:
- #3774

**Pull request merged**
