### PR TITLE
chore: "fix" test-ci-all.sh on MacOS

### LINKED ISSUE #2332: `just ci-test-all` fails on MacOS because `unshare` doesn't exist
```
$  just test-ci-all
...
## START: cli_test_always_success
00:00:00 environment: line 3: unshare: command not found
```

Not a huge deal because this script is meant for CI. But would be nice if inferior MacOS-using developer like myself could run it on our inferior machines.

### PR DESCRIPTION
**Pull request by dpc**
Fix #2332

### CODE REVIEW

**Comment by dpc** [comment]
@justinmoon Please verify.

**Comment by justinmoon** [comment]
```
00:00:00 MacOS hack: fake unshare calling: bash -c ip link set lo up && exec unshare --user ./scripts/always-success-test.sh
00:00:00 bash: line 1: ip: command not found
## FAILED: cli_test_always_success
parallel: This job failed:
cli_test_always_success
```

**Comment by justinmoon** [comment]
Seems to be stuck here for 10ish minutes:

```
## Starting all tests in parallel...
## START: cli_test_always_success
## COMPLETE: cli_test_always_success
MacOS hack: no-op run-in-namespace isolatio
```

**Comment by dpc** [comment]
> Seems to be stuck here for 10ish minutes:

Can you check processes and see if it's doing anything?

**Comment by justinmoon** [comment]
Nevermind, it was doing something.

**Comment by dpc** [comment]
> Nevermind, it was doing something.

So not only functionally deficient, but also slow? :P

Anyway, does it work?

**Comment by justinmoon** [comment]
Deficient and slow. I got to this:

```
parallel: This job failed:
cli_test_rust_tests_bitcoind
Some tests failed. Full job log:
Seq	Host	Starttime	JobRuntime	Send	Receive	Exitval	Signal	Command
1	:	1692049837.321	     0.027	0	71	0	0	cli_test_always_success
2	:	1692049842.390	   963.744	0	1625165	-1	15	cli_test_rust_tests_bitcoind
```

I think test just flaked. Let's merge and I'll keep testing.

**Review by justinmoon — APPROVED** [review]

**Pull request merged**
