### PR TITLE
feat: helper for canceling a future on task group shutdown

### PR DESCRIPTION
**Pull request by maan2003**

### CODE REVIEW

**Comment by maan2003** [comment]
how do you feel about clippy error, to me feels like we should disable that lint

**Comment by dpc** [comment]
> how do you feel about clippy error, to me feels like we should disable that lint

It seems to me it has a point, because when matching that clippy error with the diff, I wasn't sure where is the `if` even ending. :D

**Review by dpc — DISMISSED** [review]
LGTM, but clippy doesn't lie. :D

**Review by elsirion — APPROVED** [review]
Nice cleanup!

**Review by justinmoon — APPROVED** [review]

**Pull request merged**
