### PR TITLE
chore: Update LDK deps

### PR DESCRIPTION
**Pull request by benthecarman**
Don't have my dev environment fully setup but from crtl +f this seems like it'll fix for the updates

### CODE REVIEW

**Comment by benthecarman** [comment]
Not sure why CI is failing, can reproduce locally but have no idea how i broke it

**Comment by bradleystachurski** [comment]
> Not sure why CI is failing, can reproduce locally but have no idea how i broke it

Looks like sneaky semver bit us.

- `cln-rpc` in `Cargo.lock` on master is [0.1.2](https://github.com/fedimint/fedimint/blob/71856be73859716a371977458415073e50df8bbf/Cargo.lock#L830)
- updating deps in this PR bumped `cln-rpc` in `Cargo.lock` to [0.1.4](https://github.com/benthecarman/fedimint/blob/update-ldk/Cargo.lock#L809)
  - 0.1.2 -> 0.1.4 doesn't seem to be a patch :smiley:
- updating `cln-rpc` to exactly 0.1.2 fixes

I put up a [PR](https://github.com/benthecarman/fedimint/pull/1) against your branch with the update.

**Comment by elsirion** [comment]
Would be interesting to see the diff between our two diffs @bradleystachurski ^^

**Comment by bradleystachurski** [comment]
image
@elsirion I think your changes are more graceful. You rolled with the `cln-rpc` break that moved request types to `requests::` where my diff forced staying on a prior version that didn't introduce that breaking change.

**Review by m1sterc001guy — APPROVED** [review]
Ship it

Made one small issue for the deprecated API https://github.com/fedimint/fedimint/issues/3171

**Pull request merged**
