### PR TITLE
chore: use fm:: prefix for log targets

### PR DESCRIPTION
**Pull request by maan2003**
client may match some other client, we need to specify it is fedimint

### CODE REVIEW

**Review by elsirion — APPROVED** [review]
@TonyGiorgio @justinmoon if we merge this integrators should likely add these new targets as additional logging directives *now* so it doesn't get forgotten once 0.4 comes around.

**Comment by maan2003** [comment]
we could just backport it

**Comment by elsirion** [comment]
Same problem, nobody will remember when 0.3.1 is actually out and integrated because nobody cares about logging till it's needed :sweat_smile:

**Comment by maan2003** [comment]
I think `client=debug` will match `fm::client`

**Comment by elsirion** [comment]
I highly doubt that, afaik it operates on prefixes and not infixes.

**Comment by maan2003** [comment]
yep it is prefix

**Comment by maan2003** [comment]
also https://docs.rs/tracing-subscriber/latest/src/tracing_subscriber/filter/env/directive.rs.html#224

**Comment by TonyGiorgio** [comment]
> @TonyGiorgio @justinmoon if we merge this integrators should likely add these new targets as additional logging directives *now* so it doesn't get forgotten once 0.4 comes around.

Really? Changing the prefix won't show the logs unless we do something different? I don't think we've had to specify any specific logging changes so far with fedimint, it has just worked.

**Comment by elsirion** [comment]
> Changing the prefix won't show the logs unless we do something different?

Well, if you only use a global log level that gives you enough info you don't have to do anything. But if over time you discovered the components you are more interested in, then you might need to adapt your filter directives.

For example I'd recommend logging `client::reactor` with `trace` or at least `debug` level in case there's ever a weird state machine error one has to debug. For other components that's likely over the top.

**Comment by TonyGiorgio** [comment]
Gotcha. Yeah since we don't do anything specific now, happy with these changes. Thanks for the heads up.

**Review by TonyGiorgio — APPROVED** [review]

**Review by dpc — APPROVED** [review]

**Pull request merged**
