### PR TITLE
feat: port recovery tool to AlephBFT

### LINKED ISSUE #3482: Port recovery tool to Aleph Bft Consensus
The current recovery tool only supports HBBFT and has therefore been disabled when we switched to Aleph Bft.

### PR DESCRIPTION
**Pull request by bradleystachurski**
Closes #3482 

When we switched to AlephBFT, the transaction consensus items were nested in a different type so we commented out the recovery tool logic to parse the transactions from signed blocks. This PR parses transactions from `SignedBlock`s and allows the recovery tool to recover using `TweakSource::Epochs`.

I don't believe any tests exist for the recovery tool ([comment](https://github.com/fedimint/fedimint/issues/3482#issuecomment-1819763368)), so perhaps a useful followup PR can introduce tests.

### CODE REVIEW

**Comment by elsirion** [comment]
Did you test it in `just mprocs`?

**Review by elsirion — APPROVED** [review]
Looks roughly the way I imagined. Needs testing.

**Comment by bradleystachurski** [comment]
> Did you test it in just mprocs?

In progress, I wanted to kickoff CI in the meantime. Should we hold off merging until that's confirmed in `just mprocs`?

**Comment by elsirion** [comment]
Sure, I disabled auto merge :)

**Comment by bradleystachurski** [comment]
Sounds good! I'll ping once I've confirmed.

**Comment by bradleystachurski** [comment]
`just mprocs` seems to work!

Steps to reproduce
- `just mprocs`
- save output from `devimint env` (e.g. `devimint env > env_vars.txt`)
- quit mprocs (necessary to free LOCK file for db)
- export env vars from `devimint env` (e.g. `eval "$(cat env_vars.txt)"`)
- verify recovery tool works for epochs with the following command

```
nix@lenovo-m75q:~/fedimint$ FM_PASSWORD=pass ./target/debug/recoverytool --cfg "$FM_DATA_DIR/server-0" epochs --db "$FM_DATA_DIR/server-0/database" | jq
[
  {
    "descriptor": "wsh(sortedmulti(3,cP7ja5w9dE3Hx156Mb3prQH8BxFurTGj8NhJuePZAvrpymQEz7de,02113c422559f47fb21c7b2b6f8e4a9b4c595a25599780a02c6b1c586ff2120182,022dcd69db8cf8efa83cf78c47bd3d578adc2fea7aa1c3889dc458dbb0c6a2f7d0,03916b0994b703a0fd614740ab1abfe5de94ca9e03ca365e827437099a35efbc28))#0zxw5fud"
  },
  {
    "descriptor": "wsh(sortedmulti(3,cPPHZJjxVMGnsacWUnvugNcTqXx1y1djJoYFCz5M3B3DPKRAdmZd,036aed49ce719db9e34306863dfddf70879ba0b88502f14d6f6acf89a0c9712915,0386bac848c4c1fd27ba8d562bedb936b038a34f23f6a14bd660d4c85349ec088b,0231ed218323f83e890d30bf62cbe32a9d1fc8167eac6d373206b653129d6cc495))#uwpdy4ee"
  },
  {
    "descriptor": "wsh(sortedmulti(3,cVbbRBpBKLnt2hDkvPpxgvMbAyC5Ua6rQYe7WgAirL65YGCbB1SX,02d000dd13fca7fefa8033d20fece156f2c1ad3792788b96f60c15c7c273a301ac,03f418bab9350dc142826bed7ae1637b860221c2c7ef334df4e6762c35d1b1e0c8,025702b1781e700a4af0214d25d3e33a73d2940ce76a2a406be4e8f8a65b459b29))#y4l5jaw8"
  }
]
```

**Pull request merged**
