### PR TITLE
feat: spell-checking via `cargo spellcheck`

### PR DESCRIPTION
**Pull request by dpc**
It's now possible to run `just spell` to find spelling mistakes only in files modified
by us. Much more reasonable then trying to fix the whole codebase. But if you want to try
`just spell-fix-all` is still there.

**Previous message**:
I got curious and wanted to try it out, but I'm not sure if it's worth following through.

First, `cargo spellcheck` seem rather buggy and slow.

Second, it's a lot of effort. Hunspell doesn't know *a lot* of the terms we're using.

I rather get some feedback before investing any more time in it.

### CODE REVIEW

**Comment by justinmoon** [comment]
Seems like a good idea. We have had lots of typos in our codebase. This seemed to catch a lot of them. Perhaps someone else can take this over if there's a bunch of manual work remaining?

**Comment by dpc** [comment]
We should discuss on dev call, but maybe in next, next one as I'm going miss one.

**Comment by elsirion** [comment]
I don't think this is urgent, but when we find the time would be nice :)

**Review by elsirion — APPROVED** [review]

**Comment by mxz42** [comment]
I think that would certainly be nice. Currently, I have a manual list where I add spelling mistakes I come across in the code base. Wanted to submit a PR at some point fixing only typos :'D

**Comment by dpc** [comment]
@mxz42 approve & merge then and try it out! :)

**Review by justinmoon — APPROVED** [review]

**Pull request merged**
