### PR TITLE
chore(ci): use newly added `fs-dir-cache exec`

### PR DESCRIPTION
**Pull request by dpc**
It has automatic lock management, which makes unlocking 100% reliable and faster.

### CODE REVIEW

**Comment by dpc** [comment]
@bradleystachurski for awarness

**Review by bradleystachurski — COMMENTED** [review]
Looks like back-compat is failing

```
error: unrecognized subcommand 'exec'
Usage: fs-dir-cache <COMMAND>
```

**Comment by dpc** [comment]
Needed to pin it to the new revision, as it's already cached on the workers.

**Comment by maan2003** [comment]
👏 for idea to use sockets as guard

you can probably also do it for non exec version, but 

```bash
# lock
fs-dir-cache lock ... &
LOCK_PID=$!


# unlock
kill $LOCK_PID
```

**Comment by elsirion** [comment]
So either the old process cleans up the socket itself when exiting gracefully or when connecting to it the new process notices that the other end isn't listening anymore, so the new process can clean it up? That's a cool hack! Even avoids polling by just waiting for the socket to close!

**Comment by dpc** [comment]
> 👏 for idea to use sockets as guard


Yeah, I felt quite clever about it. No polling, guaranteed unlocking.

> you can probably also do it for non exec version, but exec one is good enough already

Technically there's nothing guaranteeing that the script couldn't get killed by `kill -9` before it was able to run `kill $LOCK_PID` etc. Using sockets seems 100% guaranteed, to there is still possibility that it will simply hang and hold on to the lock until killed.

I don't think we ever had cases like that, but will see how well it works in practice.

**Review by bradleystachurski — APPROVED** [review]

**Pull request merged**
