### PR TITLE
feature: split out global and module api traits

### LINKED ISSUE #2526: Create separate types for the FederationApi and ModuleApi
In order to prevent mistakenly calling an module-scoped API when you want the federation-scoped API (or vice-versa) we should make these separate types.

### PR DESCRIPTION
**Pull request by jkitman**
Fixes #2526

### CODE REVIEW

**Review by douglaz — APPROVED** [review]
LGTM

**Review by okjodom — APPROVED** [review]
Is there any chance we'd have API name and signature collisions between the global vs module scoped apis? Before this change, how would I mistakenly call one instead of the other

**Comment by jkitman** [comment]
> Is there any chance we'd have API name and signature collisions between the global vs module scoped apis? Before this change, how would I mistakenly call one instead of the other

Yeah before this both would be `IFederationApi` which we attached both global and module methods to through traits.

**Review by elsirion — COMMENTED** [review]
While it's a nicely simple fix it leaves some room for improvement: whenever both module and global API calls are to be made *two* API structs now need to be present. That's kinda unnecessary, we could instead have the ModuleAPI also expose the GlobalAPI (just not the other way around) instead.

**Pull request merged**
