### PR TITLE
feat: database in fedimint wasm client

### PR DESCRIPTION
**Pull request by maan2003**
database taken from fedi pwa. I didn't use webimint database because it uses localstorage which is unavailable in web workers and can block ui for significant time to drop frames

### CODE REVIEW

**Comment by maan2003** [comment]
how do we feel about merging this untested? In worse case we have a broken database in fedimint wasm client that nobody uses.

**Comment by m1sterc001guy** [comment]
Will this be maintained here going forward? I just wouldn't want to merge code that won't be maintained here going forward and then have another app develop on top of it thinking that it works

**Comment by maan2003** [comment]
> Will this be maintained here going forward? I just wouldn't want to merge code that won't be maintained here going forward and then have another app develop on top of it thinking that it works

Yes, we plan to maintain fedimint typescript client

**Review by m1sterc001guy — APPROVED** [review]
LGTM, I gave it a quick look, looks like this has very basic MVCC and conflict detection on writes. I assume if you're using in fedi pwa that it seems to be working. Would be good to add the tests like we have on the other db crates but I won't block on it

**Comment by maan2003** [comment]
I am just going to merge this to unblock fedimint typescript client, ideally nobody external will use this database

**Pull request merged**
