### PR TITLE
Removed the TODO about `balance_msat` field

### PR DESCRIPTION
**Pull request by Mirebella**
I addressed the TODO about renaming `balance_msat`

### CODE REVIEW

**Review by elsirion — APPROVED** [review]
Looks good, do we break any of the frontend stuff too much with that change @Kodylow ?

**Comment by elsirion** [comment]
Call: argument against: 
* possibly breaks monitoring systems
* JSON API doesn't have types, so context is useful

**Comment by Kodylow** [comment]
seriously disagree with not including unit generally. Unless we switch everything in its entirety over to msats, then have in docs that every unit is always in msats, then I think we should pass around the unit like we do.

**Comment by m1sterc001guy** [comment]
I would be in favor of just removing the todo, `balance_msat` seems fine to me

**Comment by Mirebella** [comment]
I reverted the field renaming, so the field remains unchanged. Instead I just removed the TODO.

Ready for review.

**Review by Kodylow — APPROVED** [review]

**Pull request merged**
