### PR TITLE
Share bitcoin test

### PR DESCRIPTION
**Pull request by okjodom**
Make fake bitcoin test fixture reusable across libs

### CODE REVIEW

**Comment by elsirion** [comment]
Sorry, needs a rebase now, really need a bot to tell us which PRs are compatible.

**Comment by jkitman** [comment]
Would it be less complicated if we just had `gateway-testing` depend on `integration-test`?  I image there will be other code that needs to be shared such as `FakeLightningTest`, and perhaps we also want to run gateway tests with real bitcoind when mocks are disabled.

**Comment by okjodom** [comment]
>  Would it be less complicated if we just had gateway-testing depend on integration-test?

No, but both `gateway-tests` and `integration-tests` can depend on `fedimint-testing`. This scales nicely if you want to build bespoke test suites per crate and per crate groups. `fedimint-testing` holds all base test artifacts like bitcoin / lightning mocks like you mention

**Review by elsirion — APPROVED** [review]

**Comment by elsirion** [comment]
LGTM, eventually we might want to put the testing crates into their own directory, it's getting kinda crowded in the root dir.

**Pull request merged**
