### PR TITLE
feat: gateway filter for update_gateway_cache_continuously

### PR DESCRIPTION
**Pull request by maan2003**
allows impls to ignore non vetted gateways for example

### CODE REVIEW

**Comment by elsirion** [comment]
Do you generally want to ignore them? If e.g. none were available anymore we'd probably want to fall back to unvetted ones. In that case that fn would need to hold some `Receiver<_>`/`Arc<Mutex_>>` to be told about that. Not sure this abstraction will stand the test of time.

**Comment by maan2003** [comment]
change gateway filter from `Fn(LightningGateway) -> bool` to `Fn(Vec<LightningGatewayAnnouncement>) -> Vec<LightningGatewayAnnouncement>`

the caller can detect if there are no vetted gateways

**Comment by maan2003** [comment]
this is just a filter what gateways we check for ttl, to prevent too many wakeups.

this doesn't change gateway selection

**Comment by m1sterc001guy** [comment]
Ah I see, still early for me :)

**Review by m1sterc001guy — APPROVED** [review]

**Comment by elsirion** [comment]
> this doesn't change gateway selection

The problem is that if you *might* select an unvetted GW eventually you can't tell upfront to filter out all unvetted gateways since then the selected one might expire and be unvailable. I think this can be fixed using channels, but I wonder if there's a more elegant abstraction.

**Review by elsirion — APPROVED** [review]

**Comment by maan2003** [comment]
i think gateway_filters = 
```
|gws| if gws.iter(),any(vetted) { gws.into_iter().filter(vetted).collect() } else { gws }
```

will work pretty well.

**Pull request merged**
