### PR TITLE
feat(wallet): special-case descriptor for single-guardian instances

### PR DESCRIPTION
**Pull request by elsirion**
Using p2wpkh is more efficient than a 1-of-1 multisig

### CODE REVIEW

**Comment by benthecarman** [comment]
Could also do taproot

Are no changes needed for the spending? Does miniscript handle it all here?

**Review by justinmoon — APPROVED** [review]
LGTM

**Comment by justinmoon** [comment]
Does recovery tool need to be updated to support this?

**Comment by bradleystachurski** [comment]
> Does recovery tool need to be updated to support this?

Capturing what we discussed in the dev call: We don't need to update the recovery tool to support, however it doesn't hurt to add a test case.

https://github.com/fedimint/fedimint/issues/3916

**Pull request merged**
