### PR TITLE
chore: make read-only default in recoverytool

### LINKED ISSUE #5966: Make `recoverytool` always run in read-only mode
This will prevent accidentally creating an empty DB if the DB path is incorrect and we only read anyway.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #5966

### CODE REVIEW

**Review by m1sterc001guy — APPROVED** [review]
Failed tests just look to be flakes, we'll need to debug later, but this change is certainly not the cause

**Comment by douglaz** [comment]
What's the syntax to disable it?

**Comment by douglaz** [comment]
I don't think you can disable the `readonly` now. Perhaps better just remove the flag and let it be true?

**Comment by elsirion** [comment]
> I don't think you can disable the `readonly` now. Perhaps better just remove the flag and let it be true?

Great point :see_no_evil:. I changed the PR to just always use readonly.

**Review by m1sterc001guy — APPROVED** [review]

**Review by dpc — APPROVED** [review]

**Pull request merged**
