### PR TITLE
chore: bump to v0.3.1-rc.1

### PR DESCRIPTION
**Pull request by elsirion**

### CODE REVIEW

**Comment by maan2003** [comment]
missed flake.nix

**Comment by elsirion** [comment]
Are you sure @maan2003? I checked again and couldn't find a version field in our nix files. I also remember removing it, letting nix use the version from `Cargo.toml` instead.

**Review by justinmoon — APPROVED** [review]

**Comment by maan2003** [comment]
right

**Review by maan2003 — APPROVED** [review]

**Comment by elsirion** [comment]
tagged and releasing to crates.io

**Pull request merged**
