### PR TITLE
Prefer PublicKey instead of XOnlyPublicKey for gateway references

### PR DESCRIPTION
**Pull request by okjodom**
As inspired by https://github.com/jonasnick/bips/issues/32 and the fact that I need tke `mint_pub_key` in `PublicKey` but don't know the parity with which I can type convert it

### CODE REVIEW

**Review by elsirion — COMMENTED** [review]
I think we can do this. For smart contracts I'd keep the `XOnlyPubKey`s for now as discussed on Discord due to the MuSig2 API. This will require a bunch of conversions when creating the contracts but should work without any problems imo.

**Comment by okjodom** [comment]
Closing PR for now as low pri

**Comment by elsirion** [comment]
Thought this was an issue :see_no_evil:

**Comment by elsirion** [comment]
See  #1458

**Comment by okjodom** [comment]
> See #1458

ack

**Pull request closed without merging**
