### PR TITLE
chore: update dev-running doc

### LINKED ISSUE #1814: Out of date: docs/dev-running.md
I recently setup fedimint for [dev testing](https://github.com/fedimint/fedimint/blob/master/docs/dev-running.md), and noticed that this doc is out of date. The output of these commands looks different now. Is it something that is planned to be updated at some specific release?
If not, I would like to update this doc.

### PR DESCRIPTION
**Pull request by dhruv-1001**
resolves #1814 
* update all changed cli commands output in `/docs/dev-running.md` as discussed in linked issue.

### CODE REVIEW

**Comment by dpc** [comment]
LGTM, but what happened with that png? It doesn't look like it gets deleted, yet it doesn't open or render.

**Comment by dhruv-1001** [comment]
Oh, my bad!
I updated the `tmuxinator.png`, running `git commit` command, I got this
``` shell
$ git commit -m "chore: update dev-running doc"
docs/tmuxinator.png doesn't end with a newline
Fix the problems above or use --no-verify
```
I couldn't figure out what was the problem. 
So, I tried running `echo "\n" > docs/tmuxinator.png` just for fun, and tried to commit again, this time it worked, but I forgot to check if the PNG was getting rendered and pushed the code.
I'm not sure why I'm not able to commit, can you help me with that?

Changing this PR to draft for now.

**Comment by dpc** [comment]
Try with

```
> git diff HEAD
diff --git a/misc/git-hooks/pre-commit b/misc/git-hooks/pre-commit
index ded7bd1af2..309d92f857 100755
--- a/misc/git-hooks/pre-commit
+++ b/misc/git-hooks/pre-commit
@@ -108,7 +108,7 @@ export -f check_shellcheck
 
 function check_eof() {
   errors=""
-  for path in $(echo "$git_ls_files" | grep -v -E '.*\.(ods|jpg)'); do
+  for path in $(echo "$git_ls_files" | grep -v -E '.*\.(ods|jpg|png)'); do
     # extra branches for clarity
     if [ ! -s "$path" ]; then
        # echo "$path is empty"
```

**Comment by dhruv-1001** [comment]
Yep! Works now.

**Review by elsirion — APPROVED** [review]

**Review by dpc — APPROVED** [review]
Solarized Dark FTW!

**Review by elsirion — APPROVED** [review]

**Comment by justinmoon** [comment]
Nice PR @dhruv-1001!

**Pull request merged**
