### PR TITLE
chore: move client/cli to fedimint-cli

### PR DESCRIPTION
**Pull request by justinmoon**
Most of our crates are in the top-level directory, including our new client library, so let's pull this out as well.

### CODE REVIEW

**Comment by dpc** [comment]
Markdown docs have some broken links now.

**Comment by justinmoon** [comment]
Doc test failure will be fixed once this gets merged. It's complaining that https://github.com/fedimint/fedimint/actions/runs/4624951670/jobs/8180576877?pr=2139 doesn't exist.

**Comment by mxz42** [comment]
the gateway components stay in `./gateway/` or should these be moved, too?

**Review by mxz42 — APPROVED** [review]

**Comment by justinmoon** [comment]
Will fix in a bit

**Review by dpc — APPROVED** [review]

**Comment by justinmoon** [comment]
> 
the gateway components stay in ./gateway/ or should these be moved, too?

I don't feel strongly about those. It makes a little more sense because the gateway is kind of it's own thing -- CLI, UI and daemon that are kinda independent of everything else. So a separate folder makes a bit more sense to me. Don't feel strongly about it.

**Comment by mxz42** [comment]
> CLI, UI and daemon that are kinda independent of everything else. So a separate folder makes a bit more sense to me.

I agree :+1:

**Pull request merged**
