### PR TITLE
Setup UI fixes

### PR DESCRIPTION
**Pull request by justinmoon**
trim whitespace and dash-separate guardian names because they are treated as DNS names which can't contain spaces

### CODE REVIEW

**Review by dpc — APPROVED** [review]
Should we sanity check for invalid characters?

**Comment by justinmoon** [comment]
> Should we sanity check for invalid characters?

Yea. Should probably do this on all form inputs. What characters should be considered invalid?

**Comment by dpc** [comment]
> Yea. Should probably do this on all form inputs. What characters should be considered invalid?

> DNS names can contain only alphabetical characters (A-Z), numeric characters (0-9), the minus sign (-), and the period (.). Period characters are allowed only when they are used to delimit the components of domain style names.

**Comment by elsirion** [comment]
Given that we want to migrate an API+PWA approach I'd like to avoid having too much cleverness on the server side that might creep into the API eventually. Couldn't we apply these simple fixes on the client side? Especially in the case of federation name that would be more transparent to the user too (live replace?).

**Comment by dpc** [comment]
If the server side requires dns-safe characters to work, it should do the input sanitization on the server side anyway, no? I agree that UI-side sanitization would be great, but probably in addition.

**Comment by elsirion** [comment]
Imo the server should check and fail if invalid, not apply random fixes. The client can try to nudge the user to do the right thing.

**Comment by mxz42** [comment]
> Imo the server should check and fail if invalid, not apply random fixes. The client can try to nudge the user to do the right thing.

Yes, the server *must validate* and fails if it gets invalid data.

> UI-side sanitization would be great, but probably in addition.

The client *should* also validate, so that a user has a good UX and doesn't enter all the details and then gets a bad response from the server. 


Sorry, missing a bit of context: So, we're using the guardian name as DNS name and TLS Server name indication. If we only need to derive the DNS name from the guardian name, then I'd probably be fine with replacing spaces with `-` or `_` to make it a valid DNS name *if and only if* the rest of the name contains valid DNS characters that need to be validated by the server first  (and client-side to have good UX).

**Review by okjodom — APPROVED** [review]

**Review by dpc — APPROVED** [review]

**Comment by justinmoon** [comment]
> Couldn't we apply these simple fixes on the client side? 

Yea I could do that

**Comment by elsirion** [comment]
Needs rebase

**Pull request closed without merging**
