### PR TITLE
fix: make RocksDB maximally safe

### PR DESCRIPTION
**Pull request by elsirion**
While investigating #5195 I came across the idea that RocksDB may be losing data in case of unclean shutdowns. While I don't think there's a high probability for that causing #5195, it still seems worth fixing. @m1sterc001guy lmk if I misunderstood something.

See WAL docs: https://github.com/facebook/rocksdb/wiki/WAL-Performance

<p align="center">
  Screenshot 2024-05-06 at 15-53-36 PayPerQ
  &nbsp; &nbsp; &nbsp; &nbsp; 
  Screenshot 2024-05-06 at 15-53-22 PayPerQ
</p>

### CODE REVIEW

**Comment by dpc** [comment]
Should we do it only on the client side? On the server side peer redundancy renders this less of a problem, and shutdowns happen less often. On the client side performance matters less and client gets abruptly terminated all the time.

**Review by m1sterc001guy — APPROVED** [review]
Hm RocksDb continues to amaze me. I would have thought `wal_sync=true` would have been the default option. This config seems to break the whole notion of a transaction, I'm surprised its even configurable.

**Comment by m1sterc001guy** [comment]
Perf might be impacted by this, but likely only under highly concurrently scenarios. We should see if our latency tests get any worse

**Comment by dpc** [comment]
> Perf might be impacted by this, but likely only under highly concurrently scenarios.

It's not only high concurrency scenarios. Any write to WAL will end with `fsync` which is often quite slow and will add some fixed amount of delay before it returns. On something like nvme it might be 10-100 us, on ssd 1-10ms, on hdd 10-100ms. If the system is busy it might be even higher, up to seconds.

@m1sterc001guy @elsirion

**Comment by elsirion** [comment]
I don't think perf is a concern for now. We can always optimize, but reliability should be the highest priority.

**Pull request merged**
