### PR TITLE
feat(ui): turbo dev

### PR DESCRIPTION
**Pull request by wbobeirne**
### What This Does

* Adds `yarn dev` to `fedimint-ui/` to run all `dev` commands
  * Due to there being port conflicts amongst apps, I also added `yarn dev:[app-name]` commands to only run one app at a time, along with any packages it depends on. You can specify different ports in each command to run multiple.
    * E.g. `yarn dev:guardian-ui` in one terminal, `PORT=4000 yarn dev:gateway-ui` in another terminal
    * Alternatively, we could hard-code in different ports for each app, and make them all runnable via one command?
* Fixes `yarn dev` command in `packages/ui`, a typo was causing it to fail

## Steps to Test

1. cd into `fedimint-ui` and run `yarn dev`, confirm it all runs but apps die due to port conflicts
2. run `yarn dev:guardian-ui`, confirm it runs properly on port 3000 and also runs dev for `ui`
3. run `PORT=4000 yarn dev:gateway-ui`, confirm it runs properly on port 4000 and also runs dev for `ui`

### CODE REVIEW

**Comment by elsirion** [comment]
There seems to be a problem that before calling `yarn install` the `turbo` command isn't found:

```
…/fedimint-ui $ yarn dev
yarn run v1.22.19
$ turbo run dev
/bin/sh: line 1: turbo: command not found
error Command failed with exit code 127.
```

After calling `yarn install` it works up to a point where it has compiler errors:

```
@fedimint/guardian-ui:dev: webpack compiled successfully
@fedimint/guardian-ui:dev: ERROR in src/App.tsx:3:52
@fedimint/guardian-ui:dev: TS7016: Could not find a declaration file for module '@fedimint/ui'. '/home/user/projects/minimint/fedimint-ui/packages/ui/dist/index.js' implicitly has an 'any' type.
@fedimint/guardian-ui:dev:   Try `npm i --save-dev @types/fedimint__ui` if it exists or add a new declaration (.d.ts) file containing `declare module '@fedimint/ui';`
@fedimint/guardian-ui:dev:     1 | import React, { useEffect, useMemo, useState } from 'react';
@fedimint/guardian-ui:dev:     2 | import { Box, VStack, Spinner, Heading, Text, Center } from '@chakra-ui/react';
@fedimint/guardian-ui:dev:   > 3 | import { theme, Fonts, SharedChakraProvider } from '@fedimint/ui';
@fedimint/guardian-ui:dev:       |                                                    ^^^^^^^^^^^^^^
@fedimint/guardian-ui:dev:     4 | import { GuardianApi } from './GuardianApi';
@fedimint/guardian-ui:dev:     5 | import { GuardianProvider } from './GuardianContext';
@fedimint/guardian-ui:dev:     6 | import { Setup } from './components/Setup';
@fedimint/guardian-ui:dev: 
@fedimint/guardian-ui:dev: ERROR in src/components/ConnectGuardians.tsx:17:44
@fedimint/guardian-ui:dev: TS7016: Could not find a declaration file for module '@fedimint/ui'. '/home/user/projects/minimint/fedimint-ui/packages/ui/dist/index.js' implicitly has an 'any' type.
@fedimint/guardian-ui:dev:   Try `npm i --save-dev @types/fedimint__ui` if it exists or add a new declaration (.d.ts) file containing `declare module '@fedimint/ui';`
@fedimint/guardian-ui:dev:     15 |   Icon,
@fedimint/guardian-ui:dev:     16 | } from '@chakra-ui/react';
@fedimint/guardian-ui:dev:   > 17 | import { CopyInput, Table, TableRow } from '@fedimint/ui';
@fedimint/guardian-ui:dev:        |                                            ^^^^^^^^^^^^^^
@fedimint/guardian-ui:dev:     18 | import { useConsensusPolling, useGuardianContext } from '../hooks';
@fedimint/guardian-ui:dev:     19 | import { GuardianRole, ServerStatus } from '../types';
@fedimint/guardian-ui:dev:     20 | import { getModuleParamsFromConfig } from '../utils/api';
@fedimint/guardian-ui:dev: 
…
```

**Comment by wbobeirne** [comment]
Yes, the readme tells you to run `yarn install` first before any of the commands. This is pretty standard in npm / yarn land.

**Comment by wbobeirne** [comment]
For your second issue, it looks like there's a race condition the first time you run. If ui doesn't finish dev once on the first time, you get errors, but re-running works. I'll see if I can ensure that `ui` finishes building once before starting the app.

**Comment by wbobeirne** [comment]
Alright, I fixed it so that `ui` always runs `build` before dev tasks start. I don't love the way this solution works, but at least it's bullet-proof now.

**Review by elsirion — APPROVED** [review]
Tested locally, seems to work :)

**Pull request merged**
