### PR TITLE
chore: nix flake update

### PR DESCRIPTION
**Pull request by m1sterc001guy**
Updating dependencies so CI passes again.

### CODE REVIEW

**Review by tvolk131 — APPROVED** [review]

**Comment by dpc** [comment]
I think it just needs to build a lot of stuff and times out because of it. After a retry or two it should have everything in the cache.

**Comment by m1sterc001guy** [comment]
Ugh, its a real problem, investigating

**Comment by m1sterc001guy** [comment]
Seems to be pretty consistently failing with

```
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06 2024-08-19T20:13:02.830128Z  WARN fm::devimint: failed to terminate lightningd plugins: command: lightning-cli --network regtest --lightning-dir=/build/lnv2_module-3fpP/devimint-16383-993/cln plugin stop gateway-cln-extension
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06 Caused by:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06     exit status: 2
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06     stdout:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06     stderr:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06     lightning-cli: Connecting to 'lightning-rpc': Connection refused
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:06
```

These changes have nothing to do with lightning though

**Comment by m1sterc001guy** [comment]
Might be easier just to merge https://github.com/fedimint/fedimint/pull/5871, since it changes how the `gateway-cln-extension` is used in the devimint tests, and that seems to be what is failing consistently here.

**Pull request merged**
