### PR TITLE
feat: Adds Ecash Send and Receive commands and RPCs to Gateway

### PR DESCRIPTION
**Pull request by Kodylow**
Adds functionality to directly send/receive ecash for a gateway operator. Part of the steps to make running a gateway more reasonable / manageable and exposing additional functionality for liquidity management through the new gateway UI.

### CODE REVIEW

**Review by dpc — DISMISSED** [review]

**Comment by Kodylow** [comment]
don't merge yet, found a serialization bug with DPC testing this

**Comment by Kodylow** [comment]
Fixed thank you @dpc , was double wrapping the json. Going to follow with a PR tomorrow making the gateway-client's error handling and api more reasonable

**Review by tvolk131 — APPROVED** [review]

**Review by tvolk131 — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Comment by elsirion** [comment]
Very useful!

**Comment by fedimint-backports** [comment]
Backport failed for `releases/v0.4`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/v0.4
git worktree add -d .worktree/backport-5825-to-releases/v0.4 origin/releases/v0.4
cd .worktree/backport-5825-to-releases/v0.4
git switch --create backport-5825-to-releases/v0.4
git cherry-pick -x c51b8da6f79837ded0baeb5bdbe20a34332ef7f9 746b202ec957eae7463882ba4e1ee799e6d0e4eb 7dbf032cee882c86a4a1866a99a20472c841a70f c81c4df35d688155dd3cb49692fd7c59cbccd602 4caef94be85a6e840fb47b7cb7085ee229e173fb 3078e38e6f49500adb768617c30bc7e81090701f 8328049fcb096a5e79ca9f18f0241505308a1405
```

**Pull request merged**
