### PR TITLE
chore: sign v0.3.1

### PR DESCRIPTION
**Pull request by elsirion**

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
Oh. Who got hacked?

```
--- a/releases/v0.3.1-x86_64-linux.SHA256SUMS
+++ b/releases/v0.3.1-x86_64-linux.SHA256SUMS
@@ -1,10 +1,10 @@
-a9be7f454aa1ef8639ee1b19d00604a8bb40d401683994ddb6422f0abfeef2e0  v0.3.1-x86_64-linux/fedimint-cli
-d3afa28dae92229b98023fe10a420b83e27994a83e9202129a454522150ae75e  v0.3.1-x86_64-linux/fedimint-dbtool
-367317dfe8b48e5dce9438b901fbdf712c4889149d885067b6371c778ab4d405  v0.3.1-x86_64-linux/fedimintd
+2639310b46af55c1a7f26a8be81c64102ca5ca86cb86eb9109b39ceb648dbce4  v0.3.1-x86_64-linux/fedimint-cli
+f75af756901c0639b31e6e93ba538981227aad8374bc35480c21cf3609cfe99b  v0.3.1-x86_64-linux/fedimint-dbtool
+d01283470a77227bf5d0302c4743502eaab941a258d295f79921c3781aca219d  v0.3.1-x86_64-linux/fedimintd
 76d16d78a06b3fc796bc3e8f7b013c746681e60f7ade4c0ff99e2fea7c74c148  v0.3.1-x86_64-linux/gateway-cli
 214dab77e17027fad47d1f2f1de61d878c6ed87dd18bebf9dade21b4fb04e82f  v0.3.1-x86_64-linux/gatewayd
-77fd54e08054b93226a1440bbb7f2d0b3e34beeb101cac1d4910dadcba79f81e  v0.3.1-x86_64-linux/nixos/fedimint-cli
-7c6f1d8f8907737224261f807ae85db55eb7c7633a78c25c44bbf6859391ba55  v0.3.1-x86_64-linux/nixos/fedimint-dbtool
-0c03b89363ab804708aba59e3fedccf1945c89878b1daf434572f96c438e684b  v0.3.1-x86_64-linux/nixos/fedimintd
+22a75ae2f42d3dff86267e88885e3196a6742681bed41e903a24ff8bfad0e4b6  v0.3.1-x86_64-linux/nixos/fedimint-cli
+d150651c9eefb5a154f7798aec77384742b85376f4b5b6f580ceb4140e060042  v0.3.1-x86_64-linux/nixos/fedimint-dbtool
+8a709fe9532f866e0d66d37da20b7094562ddd1a36d9bb3d32e1719ea0aa3e10  v0.3.1-x86_64-linux/nixos/fedimintd
 c5fb925df19ec53f5e1262f630cc73dac63214cca8bf94a81781cbbfa88d1708  v0.3.1-x86_64-linux/nixos/gateway-cli
 5edfdabc3af82b39d5d0f55473e55dfe2991d0111381df386b739a9f88e72aab  v0.3.1-x86_64-linux/nixos/gatewayd
```

**Comment by dpc** [comment]
Deleting `~/.cache/nix` fixed it, so I assume it's some Nix bug, which we've actually observed a handful in recent months.

**Comment by dpc** [comment]
Can you send me your binary generated with `nix build git+file:.?ref=refs/tags/v0.3.1#fedimint-cli` ?

**Comment by dpc** [comment]
Seems like the file published with the release has another hash:

```
> sha256sum ~/tmp/fedimint-cli-v0.3.1
f2eb23450d282b9e254bcbf3fbed8a8a86a0016ab3a6ba9f9931fa29982713ed  /home/dpc/tmp/fedimint-cli-v0.3.1
```

It seems the determinism broke somewhere.

**Comment by elsirion** [comment]
Good call checking against the released artifacts! I just built the binaries again on a server of mine, both with the current master and the v0.3.1 shell and am getting the same hashes :confused: 

* My local artifacts: https://sirion.io/share/v0.3.1.tar.gz

**Pull request merged**
