### PR TITLE
chore: merge fedimint-ui devshell into default shell

### PR DESCRIPTION
**Pull request by Maan2003**
also fix: our ui shell didn't have correct cargo

### CODE REVIEW

**Comment by Maan2003** [comment]
still getting errors in ui pane if I don't do yarn build in fedimint-ui/

**Comment by garyray-k** [comment]
https://github.com/fedimint/fedimint/pull/2555

Related.

**Comment by okjodom** [comment]
LGTM, if we never want specialized shells and customization for UI development

**Review by dpc — APPROVED** [review]

**Review by elsirion — APPROVED** [review]
LGTM

**Pull request merged**
