### PR TITLE
feat: `just final-check`

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Review by elsirion — APPROVED** [review]

**Comment by justinmoon** [comment]
How does this compare with https://github.com/fedimint/fedimint/blob/master/scripts/final-checks.sh

IMO we should only have one "final check". Justfile is the right place to define it because it's more discoverable there.

**Comment by dpc** [comment]
> IMO we should only have one "final check". Justfile is the right place to define it because it's more discoverable there.

Yeah, but they are doing slightly different things, and I'm not sure if they are reasons for it. I think we can kill `./script/final-checks.sh` after we have some time getting used to `just final-check` and making sure it works OK.

**Comment by justinmoon** [comment]
Works for me. I think @jkitman is the main user of `final-checks.sh` script ...

**Review by justinmoon — APPROVED** [review]

**Comment by jkitman** [comment]
So this `final-check` builds wasm and runs tests?  Perhaps a better name is in order?

I'm okay if you want to remove the shell script, I can just script it locally.

**Comment by justinmoon** [comment]
> I'm okay if you want to remove the shell script, I can just script it locally.

If you find it useful, I think we should have a just command for it. Probably best to have just commands for all developer-facing scripts so that they're more discoverable.

**Pull request merged**
