### PR TITLE
Fedimint DB DUMP

### PR DESCRIPTION
**Pull request by m1sterc001guy**
Fedimint DBDUMP is a tool to dump the contents of the rocksdb in either the client or the server. The path to the database is a required parameter and the range and prefix to dump are optional parameters. Adding a range or a prefix will filter the output of the database by the range within the database and/or the prefix within the range. The prefix is defined by the enum DbKeyPrefix is the respective modules.

For more information on the ranges and prefixes available, see https://github.com/fedimint/fedimint/blob/master/docs/database.md. Table headers are ranges and the Name column are prefixes.

Usage:
    fedimint-dbdump <path> [--range=<range>] [--prefix=<prefix>]
    
Options:
    --range=<range>    A CSV list of the ranges of the database to dump [default: All].
    --prefix=<prefix>  A CSV list of he prefixes within the range of the database to dump [default: All].

    RANGES=consensus,mint,wallet,lightning,mintclient,lightningclient,walletclient

Issue: https://github.com/fedimint/fedimint/issues/331

### CODE REVIEW

**Comment by elsirion** [comment]
Need to play around with it a bit, but we probably also want a `flake.nix` entry for the dbdump tool: https://github.com/fedimint/fedimint/blob/c0f8ee2af2407996fe8258e5869c4b7cb2143d17/flake.nix#L500-L524

**Comment by elsirion** [comment]
Also needs a rebase, sorry :grimacing:

**Comment by m1sterc001guy** [comment]
Rebased, added fedimint-dbdump to flake.nix, and made a small change in main.rs of dbdump.

**Review by elsirion — APPROVED** [review]
Minor nit: the top level keys are annoying to use since they contain spaces. E.g.:

```json
    "Peg Out Bitcoin Transaction": [
      [
        {
          "txid": "c84594bc180a25cbe2abfe7d10a45162e537204e3f88573ebfa5bb8eb13b9b67",
          "out_idx": 0
        },
        "8a32c224dac9015113105e27fdaf601c0831b92e8b6fce8cf865f9af2c51dc1e"
      ]
    ],
```

Unrelated to the tool: It would be cool to have some tests that check if certain data is removed from the DB to not accidentally open ourselves to DoS in ways we aren't aware of.

Making all the DB values `Serialize` will interfere with modularization (#946), but I'll figure it out.

**Pull request merged**
