### PR TITLE
 chore: add ClientHandle::restart 

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Comment by maan2003** [comment]
LGTM, will try it out

**Comment by maan2003** [comment]
https://github.com/fedimint/fedimint/pull/4538

**Review by maan2003 — APPROVED** [review]

**Review by justinmoon — APPROVED** [review]

**Comment by dpc** [comment]
Rebased.

**Comment by maan2003** [comment]
@dpc still conflicts, rebase on top of https://github.com/fedimint/fedimint/pull/4492

**Comment by maan2003** [comment]
lets just merge https://github.com/fedimint/fedimint/pull/4538, github really struggle with PRs on top of each other

**Pull request closed without merging**
