### PR TITLE
chore: build and upload deb&rpm binaries 

### PR DESCRIPTION
**Pull request by dpc**
Rework of #2771

Mostly w.r.t moving deb&rpm bundling to a step that already built these packages anyway.

### CODE REVIEW

**Comment by dpc** [comment]
Forced it to run with a little hack in [7d4ce8d](https://github.com/fedimint/fedimint/pull/2859/commits/7d4ce8d6618a63a1bccd6e03e40ab0d27073e92b) and it seems to work: https://github.com/fedimint/fedimint/actions/runs/5698856903/job/15447167236?pr=2859

**Review by elsirion — APPROVED** [review]
Really cool!

**Comment by justinmoon** [comment]
Are the packages actually uploaded anywhere?

**Comment by dpc** [comment]
@justinmoon 

image

It seems so.

**Comment by dpc** [comment]
image


Client one looks suspiciously small, but that can be fixed.

**Comment by justinmoon** [comment]
IIRC we can also build universal binaries that can run on any distro? Should build and upload those as well?

**Comment by dpc** [comment]
@justinmoon #2885

**Pull request merged**
