### PR TITLE
WIP: allow setting up federation via `fedimint-cli`

### LINKED ISSUE #3795: Allow setting up federation via `fedimint-cli admin …` commands
This seems easier than learning typescript.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #3795

### CODE REVIEW

**Comment by dpc** [comment]
@elsirion It seems you've forgot about this one.

**Comment by douglaz** [comment]
This feature is very important

**Comment by elsirion** [comment]
:see_no_evil:

**Comment by justinmoon** [comment]
Looks like this is no longer needed after https://github.com/fedimint/fedimint/pull/4628

**Pull request closed without merging**
