### PR TITLE
Unify `*Registry` types with a common macro 

### PR DESCRIPTION
**Pull request by dpc**
So they can maintain consistent apis (where desired).

On top of #1285. Please review that first, then click Update here. :)

### CODE REVIEW

**Comment by elsirion** [comment]
Are you sure it could not be a generic type instead? The main reason it wasn't was that getters referenced the type stored in there, but that's now changed.

**Comment by dpc** [comment]
> Are you sure it could not be a generic type instead? The main reason it wasn't was that getters referenced the type stored in there, but that's now changed.

They could, yes.

I was thinking about it, but then technically they are all going to be the same root type, with a different parameter, error messages and documentation might be less clear in places.

AFAIK the `<M>` is there only for `Backend` vs `Server` module registries, because there were some thing that could be generic over backend vs fronted, and it could be useful. For `decoder` it doesn't seem to make sense.

I don't feel strongly about it, but my initial feel was they would be better of as macro-generated distinct types. Reminds me of bitcoin hashes which are also macro based https://github.com/rust-bitcoin/rust-bitcoin/blob/master/hashes/src/sha256.rs . IIRC it's somewhat similar situation. With macros we could still add some traits that all implement. Or we could revert back and forth if we find a good reason for it.

**Comment by elsirion** [comment]
I'm not a big fan of macros where they can be reasonably avoided. Tooling support inside them is poor, so refactoring anything related to macros is a pain. If the only reason to go with a macro over a generic+typedef approach is compiler error messages I highly prefer generics.

**Comment by dpc** [comment]
> I'm not a big fan of macros where they can be reasonably avoided. 

All, right will get it done using generics then, after @mxz42 is done with the renames.

**Comment by dpc** [comment]
Superseded by https://github.com/fedimint/fedimint/pull/1364

**Pull request closed without merging**
