### PR TITLE
fix: back-compat ci tests are marking everything as :red-x:

### PR DESCRIPTION
**Pull request by dpc**
And it's just annoying. :shrug:

image

I look at my PRs and it's not clear to me if something failed in them or not. On the other hand when looking at PRs I could review, I can't tell if they are still being fixed or passing.

### CODE REVIEW

**Comment by bradleystachurski** [comment]
This fixes the last broken test. Would you still prefer to disable all backwards-compatibility tests?

https://github.com/fedimint/fedimint/pull/4166

**Comment by dpc** [comment]
> This fixes the last broken test. Would you still prefer to disable all backwards-compatibility tests?
> 
> #4166

Let's wait then. :)

**Review by justinmoon — APPROVED** [review]

**Review by bradleystachurski — APPROVED** [review]
Might be worth keeping this PR around and approved if we want to disable CI quickly, even though we're going to see how things go after all the backwards-compatibility fixes are merged

**Review by Maan2003 — APPROVED** [review]

**Comment by dpc** [comment]
Will let it slide... this time. ;)

**Pull request closed without merging**
