### PR TITLE
simplify: do not stage config

### PR DESCRIPTION
**Pull request by joschisan**
Not writing to disk in the ConfigGenApi  makes it easier to reason about the behaviour of the ConfigGenApi struct as it is conceptually encapsulated. Now FedimintServers behaviour only depends on files that it has written to disk itself while ConfigGenApi has no side effects. Furthermore, a crashed config gen starts from a clean slate and does not have to deal with potential remnants.

### CODE REVIEW

**Review by elsirion — CHANGES_REQUESTED** [review]
ConceptNACK: staging was added on purpose to avoid a potential bug  from accidentally deleting the live guardian config. CC @justinmoon who originally proposed this.

**Comment by joschisan** [comment]
@elsirion Could you please elaborate on the issue and why staging avoids it?

**Comment by elsirion** [comment]
We only have code that can delete files in staging, not the final config directory, so if that function is called by accident nothing too had should happen.

**Comment by joschisan** [comment]
@elsirion This pr does not introduce any code to delete the config files either; the config is only written to disk after the start_consensus method has been called.

**Comment by elsirion** [comment]
After taking a deeper look at the code what you want to do is postponing writing of the config till DKG is finished and configs have been verified. That way we don't have to delete anything anymore when resetting the cofiggen process. One drawback of this is that you cannot restart `fedimintd` mid-setup anymore, which iirc was the reason for going with this approach, but we never really tested it, so I think we could just do away with this feature and this PR looks ok at a high level.

**Review by elsirion — DISMISSED** [review]

**Comment by elsirion** [comment]
Needs rebase :(

**Review by tvolk131 — APPROVED** [review]

**Review by dpc — APPROVED** [review]

**Pull request merged**
