### PR TITLE
chore: Mock RPCs between Client -> Gateway

### PR DESCRIPTION
**Pull request by m1sterc001guy**
Working towards: https://github.com/fedimint/fedimint/issues/5168

Gets rid of the ugly hack we used of removing the gateway's clients during the tests.

### CODE REVIEW

**Comment by m1sterc001guy** [comment]
@dpc fixes one of the sores of the lightning tests, next step is to convert the other tests to devimint tests and then rip out the real LN part

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
I think I've just seen a flake caused by the problem this fixes, so hitting the land button and adding the label to get more reviews later.

**Comment by dpc** [comment]
Unrelated flake we are already working on a fix in #5182

**Comment by elsirion** [comment]
Great work! We should strive to be able to mock out all network connection so that we can test state machines in module-local tests that don't need a whole devimint setup!

**Pull request merged**
