### PR TITLE
Rename MINIMINT_TEST_REAL to MINIMINT_TEST_DISABLE_FIXTURES

### PR DESCRIPTION
**Pull request by dpc**
IMO, "real" does not convey the meaning well. "Against real
nodes" would be OK, but seems to long.

### CODE REVIEW

**Comment by dpc** [comment]
Just an idea. If you see a better name, please let me know.

**Review by elsirion — APPROVED** [review]
Sounds like a better name

**Comment by justinmoon** [comment]
I find this kind of confusing, initially: `export MINIMINT_DISABLE_FIXTURES=0`

Are `lightningd` / `bitcoind` the fixtures being disabled? Or are the mocked `lightningd` / `bitcoind` the fixtures? Both qualify in my mind. "fixture" is ambiguous

As background, "real" / "fake really correspond to which of [these rust modules](https://github.com/fedimint/fedimint/tree/master/integrationtests/tests/fixtures) should be used by our rust integration testing framework.

I would prefer something like `FM_MOCK_BITCOIND_AND_LIGHTNINGD`.

**Comment by elsirion** [comment]
Oh, sorry, I assumed "fixture" meant something being mocked. The @jkitman test suite was the first time I ever encountered that word tbh. My bad for merging, sounded reasonable.

**Comment by justinmoon** [comment]
> My bad for merging

No worries. Curious what @jkitman thinks.

**Comment by dpc** [comment]
> Oh, sorry, I assumed "fixture" meant something being mocked.

This is also what it means to me. Colloquially, prepared fixed data returned by mocks or otherwise used in testing are called fixtures. I googled some definitions and sure, technically real daemon instances would maybe qualify as "fixtures" per some definitions because they are "fixed in place for the purpose of testing", but IMO it's stretching it.

Anyway - I'm fine with find finding a better name. `FM_MOCK_BITCOIND_AND_LIGHTNINGD` seems OK, but has reversed meaning, IMO. The default (no envs set) should be using mocks. And the env flag should should mean "now talk to actual daemons".

**Comment by dpc** [comment]
Hmmm... I started looking deeper into the tests and the "fake" implementations are not even "fixtures" , but more of full simulated implementations. So I `DISABLE_FIXTURES` doesn't work at all.

**Pull request merged**
