### PR TITLE
feat(spend): convert `amount` postional to named arg

### PR DESCRIPTION
**Pull request by 15IITian**
#3822

### CODE REVIEW

**Comment by elsirion** [comment]
Not worth it imo as it would require a branch in our test suite to pass backwards compatibility testing. @bradleystachurski would you agree? @dpc thoughts as the biggest fan of named arguments I know? :P

**Comment by bradleystachurski** [comment]
Agreed, we should wait for backwards-compatibility in CI 👍 

I'd expect this will break compatibility similar to `--mnemonic` (https://github.com/fedimint/fedimint/issues/4016).

I do think it'd be good to establish a pattern for updating our CLI in a backwards-compatible way, but I'd expect that'll wait until we fix `mnemonic`.

**Comment by 15IITian** [comment]
> Not worth it imo as it would require a branch in our test suite to pass backwards compatibility testing. @bradleystachurski would you agree? @dpc thoughts as the biggest fan of named arguments I know? :P

If there is such a case -> then please filter out the required work to do.
#3822

**Comment by dpc** [comment]
:shrug:

**Comment by elsirion** [comment]
I'll close this for now. Feel free to open issues for things you want to work on first so we can discuss the design/if it makes sense to do for the project right now.

**Comment by 15IITian** [comment]
@elsirion  
can I work on #3822 second last task?

**Pull request closed without merging**
