### PR TITLE
chore: fix clippy warnings

### PR DESCRIPTION
**Pull request by tvolk131**

### CODE REVIEW

**Review by m1sterc001guy — DISMISSED** [review]
Needs rebase

**Comment by tvolk131** [comment]
> Needs rebase

Rebased!

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
Adding backport label, as I don't want to live with these forever during 0.4 maintaince.

**Comment by fedimint-backports** [comment]
Backport failed for `releases/v0.4`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/v0.4
git worktree add -d .worktree/backport-5606-to-releases/v0.4 origin/releases/v0.4
cd .worktree/backport-5606-to-releases/v0.4
git switch --create backport-5606-to-releases/v0.4
git cherry-pick -x 1eb456c78c37f59b1188beae21478c30f299d056
```

**Pull request merged**
