### PR TITLE
Add a new threshold key for authenticating the configuration

### PR DESCRIPTION
**Pull request by jkitman**
First task in #1205

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Comment by justinmoon** [comment]
Stupid question: why can't we use the same key for authenticating configs *and* epoch history

**Comment by elsirion** [comment]
That's a very good point :sweat_smile:

**Comment by justinmoon** [comment]
> That's a very good point 😅 EDIT: we'd need to do tagged hashing, but it would work.

Why would we need to do tagged hashing?

**Comment by elsirion** [comment]
Let's say the byte string `[0xde, 0xad, 0xbe, 0xef]` is both a valid config and epoch, then an attacker could use the signed config to inject a fake epoch or the other way around.

If we prefix the signed data though this is no longer a problem. Let's say `0x01` is the prefix for epochs and `0x02` is the prefix for configs, then what would be signed would be `[0x01, 0xde, 0xad, 0xbe, 0xef]` or `[0x02, 0xde, 0xad, 0xbe, 0xef]` respectively, i.e. not interchangeable anymore.

Since the message is hashed, the prefixing is typically done in the hash function and e.g. [`bitcoin_hashes` has support for tagged hashing](https://docs.rs/bitcoin_hashes/0.11.0/bitcoin_hashes/sha256t/index.html). Doing the tagging in the hash function has the benefit that the tag does not actually have to be hashed every time, one can instead hash it once and cache the hasher's internal state.

**Pull request merged**
