### PR TITLE
chore(flake): expose fedimint-dbtool output

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Review by Maan2003 — APPROVED** [review]

**Review by justinmoon — APPROVED** [review]
Plz backport

**Comment by fedimint-backports** [comment]
Git push to origin failed for releases/v0.2 with exitcode 1

**Comment by elsirion** [comment]
GitHub actions are apparently not allowed to change themselves: https://github.com/fedimint/fedimint/actions/runs/7588947714/job/20672549869#step:3:50

Skynet averted for now.

**Comment by dpc** [comment]
Backport: #4105

**Pull request merged**
