### PR TITLE
chore: split backend test for bitcoind

### PR DESCRIPTION
**Pull request by dpc**
It has a bit long runtime, and each module can just run in parallel to bring it down.

### CODE REVIEW

**Comment by dpc** [comment]
@m1sterc001guy Seems like `env FM_TEST_ONLY=bitcoind-ln-gateway` is actually the slowest one there. If we could figure out a way to split it in 2 or 3, that would be a win.

**Comment by dpc** [comment]
@m1sterc001guy i've split it in half

**Comment by bradleystachurski** [comment]
@dpc Did you have a chance to run locally? Bumping into a familiar error starting lightningd since the path is too long.

```
00:00:00 2024-04-30T05:50:36.867177Z  INFO fm::devimint: Devimint data dir path=/tmp/nix-shell.qfYw9L/backend_test_ln_gateway_not_client-9AF7/devimint-2801155-576
00:01:01 Error: Polling lightningd failed after 111 retries (timeout: 60s)
00:01:01
00:01:01 Caused by:
00:01:01     0: connect to lightningd
00:01:01     1: path must be shorter than libc::sockaddr_un.sun_path
```

**Comment by dpc** [comment]
@bradleystachurski I don't think that's the case anymore in the latest version I pushed 3h ago.

**Comment by bradleystachurski** [comment]
I'm getting that error against the latest commit

```
nix@lenovo-m75q-ubuntu:~/fedimint$ git rev-parse HEAD
773ff57051aa0b38e5b89699ce8b92e58090ee03
```

Using a shorter test name for `backend_test_ln_gateway_not_client` passes locally.

**Review by bradleystachurski — APPROVED** [review]

**Pull request merged**
