### PR TITLE
Rename mint-cilent to fedimint-client-legacy

### PR DESCRIPTION
**Pull request by justinmoon**
Try to differentiate the legacy and new clients in the name of the crates themselves.

Also -- most of our crates are in the top-level directory, including our new client library, so let's pull this out as well.

Builds on https://github.com/fedimint/fedimint/pull/2139

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Review by mxz42 — DISMISSED** [review]

**Comment by mxz42** [comment]
cross compile doesn't pass. 

```
       > ++ command cargo build --profile release --target wasm32-unknown-unknown --package mint-client
```

needs change in [justfile](https://github.com/fedimint/fedimint/blob/master/justfile#L56) I think.

**Comment by dpc** [comment]
Lots of conflicts. The build failure is due to 

`flake.crane.nix`, `client-pkgs` section `dirs` filtering.

**Comment by justinmoon** [comment]
Passing CI now. Sorry!

**Review by dpc — APPROVED** [review]

**Review by mxz42 — APPROVED** [review]
nice :+1:

**Pull request merged**
