### PR TITLE
chore: bump nixpkgs

### PR DESCRIPTION
**Pull request by Maan2003**
I couldn't try it locally.

### CODE REVIEW

**Comment by elsirion** [comment]
Apparently nix 23.05 doesn't ship with this patch yet :( https://github.com/ElementsProject/lightning/commit/ff0a63a0d7149100bff9c00ba5cf120e8daead7a

**Comment by dpc** [comment]
Needs

```
-            NIX_CFLAGS_COMPILE = "-Wno-stringop-truncation";
+            NIX_CFLAGS_COMPILE = "-Wno-stringop-truncation -Wno-error=maybe-uninitialized";
```

to fix compiling clightning, but after that the dev shell works and RA seems to work as well.

**Comment by justinmoon** [comment]
There's also a lot of semgrep warnings about `tokio::time`

**Comment by dpc** [comment]
Probably good time to bump everything anyway.

**Comment by dpc** [comment]
I see that cross-compilation is breaking as well. Possibly some paths in `androidCrossEnvVars = ''` in `flake.toolchain.nix` might need changing after ndk version changed.

**Comment by Maan2003** [comment]
there are some output collisions in cargo doc, maybe new cargo version?

**Comment by dpc** [comment]
Looks like `bitcoincore-rpc v0.16.0` pulls in `base64-compat v1.0.0` which is pretending to be `base64` which in the recent version of `cargo` angers `cargo doc`.

Maybe there's some hack to make it work that I missed, but `bitcoincore-rpc v0.17.0` seem to have dropped that package. However this depends on `bitcoin 0.30.0`.

**Comment by dpc** [comment]
Yeap. We'd need to update to bitcoin 0.30, and https://crates.io/crates/esplora-client/0.5.0/dependencies doesn't seem to support it yet.

**Comment by dpc** [comment]
https://github.com/bitcoindevkit/rust-esplora-client/pull/51

**Comment by dpc** [comment]
cln-rpc still on bitcoin 0.29.1 https://crates.io/crates/cln-rpc/0.1.3/dependencies and I don't see any issue or PR about it

**Comment by dpc** [comment]
Moved bumping the bitcoin dependency to https://github.com/fedimint/fedimint/pull/2667

**Comment by dpc** [comment]
Landed in another PR in the meantime.

**Pull request closed without merging**
