### PR TITLE
tests: added unit test in fedimint-core/src/util/update_merge.rs

### LINKED ISSUE #5122: tests: missing unit test in fedimint/fedimint-core/src/util/update_merge.rs
### Description

Currently, unit test are missing in fedimint/fedimint-core/src/util/update_merge.rs

### Use case

The proposed solution is to address this by adding the necessary tests for the files in the bytes package, which would help in detecting bugs early, supporting CI/CD, reducing debugging time, providing safety for this codebase etc...

### PR DESCRIPTION
**Pull request by sivasathyaseeelan**
### Fix
This PR adds unit test fin fedimint/fedimint-core/src/util/update_merge.rs and closes #5122

### CODE REVIEW

**Review by dpc — DISMISSED** [review]

**Comment by elsirion** [comment]
Lint check is failing, looks like you didn't run `just format` before committing. Please do so and **amend** the commit, don't create a second commit.

**Comment by sivasathyaseeelan** [comment]
> Lint check is failing, looks like you didn't run `just format` before committing. Please do so and **amend** the commit, don't create a second commit.

@elsirion @dpc I've just run `just format` and amended the commit. Could you please review it again?

**Review by dpc — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Review by maan2003 — COMMENTED** [review]
missed the main tricky case: one future passing and other future failing should result in 
(fail, pass) or (pass, pass) depending on order.

**Comment by maan2003** [comment]
and also ensuring that no two futures are run concurrently

**Pull request merged**
