### PR TITLE
chore: bump build timeout

### PR DESCRIPTION
**Pull request by tvolk131**
Prompted by the difficulty in merging #4968

### CODE REVIEW

**Review by dpc — APPROVED** [review]
Our tests in MQ got waaay too slow. Something is wrong there.

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/issues/4926 might be related

**Review by maan2003 — APPROVED** [review]

**Comment by dpc** [comment]
Possibly #5019 will make unnecessary. We can't be waiting 1.5h for a MQ to merge stuff.

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
I need to look more into it.

**Pull request merged**
