### PR TITLE
fix: don't depend on std features from lightning-invoice

### LINKED ISSUE #3837: Client should not rely on `std` features of `lightning-invoice`
This is a problem for Munitnywallet: https://discord.com/channels/990354215060795454/990354215878688860/1181358717606834246

2023-12-05-110832_5120x1441_scrot

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #3837. Would be awesome if you could test this today @TonyGiorgio so we can get it into 0.2.0.

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
No, not working. Still uses `is_expired()` which is also being a `std` flag. We'll probably just edit our fork of LDK to allow some of the `std` flags in wasm32 that don't explicitly use `SystemTime::now()`.

**Comment by elsirion** [comment]
Ahhh, damn it. I removed all the *added* calls to non-std functions, `is_expired` existed before, but I didn't consider that I moved it from the gateway to the client crate. So you should be able to just add that function as `unimplemented!` to your fork, let's figure out a way to test that we don't use std there longer term (#3838).

**Comment by TonyGiorgio** [comment]
Thanks for your help. Added a comment there. I'll try a few things out in our patch and get it working again. Thank you!

**Comment by TonyGiorgio** [comment]
Actually, you may want to pull out `is_expired()`, it calls `SystemTime::now()`. I can add `unimplemented` or `false` on our end but you'll run into this as well running the fedimint client in any wasm32 environment

```
	#[cfg(all(feature = "std", not(target_arch = "wasm32")))]
	pub fn is_expired(&self) -> bool {
		Self::is_expired_from_epoch(&self.timestamp(), self.expiry_time())
	}

	/// Returns whether the expiry time from the given epoch has passed.
	#[cfg(all(feature = "std", not(target_arch = "wasm32")))]
	pub(crate) fn is_expired_from_epoch(epoch: &SystemTime, expiry_time: Duration) -> bool {
		match epoch.elapsed() {
			Ok(elapsed) => elapsed > expiry_time,
			Err(_) => false,
		}
	}
```

```
    #[stable(feature = "time2", since = "1.8.0")]
    pub fn elapsed(&self) -> Result<Duration, SystemTimeError> {
        SystemTime::now().duration_since(*self)
    }
```

**Comment by elsirion** [comment]
Currently this `is_expired` fn is only called on the gateway and not the user client. But I'll fix, just not sure if worth backporting.

**Pull request merged**
