### PR TITLE
chore: switch to using jemalloc on all major binaries.

### LINKED ISSUE #6334: Likely memory leak
Fedi discovered a likely memory leak after upgrading an internal testing federation from 0.3 to 0.4. It looks very logarithmic, so it might not be a memory leak, but just a data structure with this behavior (some rocksdb in-memory index?). 

fedi-internal

In general this shouldn't be a huge problem for setups with automatic restart: the OOM killer will kill the process and systemd will restart it. Might still lead to wonky behavior.

Some starting points for debugging:

> 1. **Valgrind:**
> 
>    - Although Valgrind is primarily a tool for C/C++ programs, it can still be used with Rust programs to detect memory leaks. Compile your program with debuginfo and run it with Valgrind:
>      ```bash
>      cargo build --release
>      valgrind --leak-check=full ./target/release/your_program
>      ```
> 
> 2. **Heaptrack:**
> 
>    - Heaptrack tracks all memory allocations and can give detailed insights into which parts of your code are causing memory issues.
>    - To use it, install heaptrack and run it with your Rust executable:
>      ```bash
>      heaptrack ./target/debug/your_program
>      heaptrack_gui heaptrack.your_program.<timestamp>.gz  # Use GUI to analyze
>      ```
> 
> 3. **AddressSanitizer:**
> 
>    - You can compile your Rust program with AddressSanitizer to detect memory errors. Set the RUSTFLAGS environment variable:
>      ```bash
>      export RUSTFLAGS="-Zsanitizer=address"
>      export RUSTDOCFLAGS="-Zsanitizer=address"
>      cargo +nightly build
>      ./target/debug/your_program
>      ```
> 
>    - Note that AddressSanitizer support might require a nightly compiler and additional setup.

### PR DESCRIPTION
**Pull request by dpc**
"reverse backport" of #6354 

Fix #6334

### CODE REVIEW

**Review by bradleystachurski — COMMENTED** [review]
There are some open questions on the PR targeting `releases/v0.4`. Once that lands, I think we're good to merge to `master` and `releases/v0.5`.

**Review by elsirion — APPROVED** [review]

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.5`:
- #6383

**Comment by fedimint-backports** [comment]
Backport failed for `releases/v0.4`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/v0.4
git worktree add -d .worktree/backport-6357-to-releases/v0.4 origin/releases/v0.4
cd .worktree/backport-6357-to-releases/v0.4
git switch --create backport-6357-to-releases/v0.4
git cherry-pick -x e4517a9a3d6b144efc1bd632ff74f2ee3ae6945e 5e21fcdc64c03753b4503c9293404113fadd4301 63db50b00ae5ac40ccab1271141a16e0b182371e
```

**Comment by fedimint-backports** [comment]
Backport failed for `releases/v0.5`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/v0.5
git worktree add -d .worktree/backport-6357-to-releases/v0.5 origin/releases/v0.5
cd .worktree/backport-6357-to-releases/v0.5
git switch --create backport-6357-to-releases/v0.5
git cherry-pick -x e4517a9a3d6b144efc1bd632ff74f2ee3ae6945e 5e21fcdc64c03753b4503c9293404113fadd4301 63db50b00ae5ac40ccab1271141a16e0b182371e
```

**Pull request merged**
