### PR TITLE
fix: choose minimal block count or unix time

### PR DESCRIPTION
**Pull request by joschisan**

### CODE REVIEW

**Comment by dpc** [comment]
Why? :) (The answer would be best done as a comment in the code)

**Comment by bradleystachurski** [comment]
One example for a 3/4 federation.
```
95 100 1000 1000
    |   |
    |   median
    |
    max_evil
```

**Review by dpc — CHANGES_REQUESTED** [review]
Comments. :) "Why?"

**Comment by joschisan** [comment]
@dpc @bradleystachurski please review the comments

**Review by dpc — APPROVED** [review]

**Comment by elsirion** [comment]
This is a consensus-breaking change, are we committing to implementing non-additive consensus change support for 0.5?

**Pull request merged**
