### PR TITLE
fix: enable cross-compilation to android from macos

### PR DESCRIPTION
**Pull request by dpc**
Previously we were blocked on on lack of android SDK, but justin pointed me at:

https://github.com/tadfisher/android-nixpkgs

which should do the job.

### CODE REVIEW

**Comment by justinmoon** [comment]
I was successfully able to run the following from my m1 mac from the `nix develop --ignore-environment .#cross` shell:

```
cargo check -p fedimint-client-legacy --target aarch64-linux-android
cargo check -p fedimint-client-legacy --target x86_64-linux-android
cargo check -p fedimint-client-legacy --target armv7-linux-androideabi
```

🎉

**Review by justinmoon — APPROVED** [review]

**Review by elsirion — APPROVED** [review]
Works for me too

**Comment by justinmoon** [comment]
> Works for me too

To be clear, this shouldn't change anything for you unless you're compiling **from** MacOS **targeting** Android

**Comment by dpc** [comment]
@justinmoon We switch to new toolchain for Linux users as well, so there is a chance something would broke on Linux.

**Pull request merged**
