### PR TITLE
Gateway CLI

### PR DESCRIPTION
**Pull request by okjodom**
I was looking into decoupling Gateway Pegin + Pegout RPC methods from CLN plugin implementation, a step necessary to unblock gateway support for multiple federations.

To achieve the objective, this PR proposes a Gateway CLI which makes rpc calls to  new endpoints on the gateway webserver.

### Auhenticaton

- [ ] TODO: #807 -  **we need to figure out some authentication strategy for the gateway webserver** otherwise anyone can POST `/withdraw <amount> <address>` on the gateway url and we end up with a rekt gateway!

Reference: [Discord: Pegin + Pegout for Gateways ](https://discordapp.com/channels/990354215060795454/1030896484687818873)

### CODE REVIEW

**Review by justinmoon — APPROVED** [review]

**Comment by justinmoon** [comment]
Looks good. Obviously some TODOs that still need fixing, but let's just iterate on master.

**Comment by justinmoon** [comment]
I think it would be better to expose this functionality behind something like `fedimint-cli --gateway` instead of a whole new `gateway-cli`. But this is something we can figure out in the future.

**Comment by okjodom** [comment]
> I think it would be better to expose this functionality behind something like fedimint-cli --gateway instead of a whole new gateway-cli. But this is something we can figure out in the future.

Maybe. Would be nice, assuming gateway and fedimint are co-located.
There are trade-offs to separation of concerns

**Comment by elsirion** [comment]
I like the `fedimint-cli gateway [--gateway <gw_id|ur>] <subcommand>` idea a lot. The gateway API could come out of the client DB while the authentication info (macaroons? some other bearer token?) is stored in a separate file in the client directory.

The counter argument against unifying the commands is that a gateway doesn't need a federation to exist, so there shouldn't be a dependency. This can be mitigated by allowing the optional specification of a gateway url.

**Pull request merged**
