### PR TITLE
202302/rename to `Dyn`s

### PR DESCRIPTION
**Pull request by mxz42**
Adding the `Dyn` prefix to 2 structs

### CODE REVIEW

**Comment by dpc** [comment]
Do we want `Dyn` on everything? We needed it most on module types, as there we wanted the shortest name to go to 3rd party module writers.

Here we can use `Foo` + `IFoo` and the fact that it's `Dyn` is not something I need reminder in name, IMO.

**Comment by mxz42** [comment]
hm, I just came across these today and thought that may fight the pattern.

valid argument, though. 

thoughts? @elsirion @jkitman

**Comment by elsirion** [comment]
Imo consistency would be nice and seeing on first glance that it's a mockable interface would be good too, but I see your point of longer names @dpc (and would add that it is also more churn).

**Comment by mxz42** [comment]
closing this in favor of the more general issue #2055

**Pull request closed without merging**
