### PR TITLE
Make mint module associated types enums for extensibility

### LINKED ISSUE #3570: Make all module associated types enums for extensibility
Depends on #3569

### PR DESCRIPTION
**Pull request by elsirion**
Part of #3570

The strategy implemented here is:
* Make input/output/output outcome/consensus item types enums with only one main `V0` variant for now and a `Default` variant that is used when encountering an unknown variant on deserialization.
* **Server:** throw error when encountering `Default` variants as we don't understand the semantics
* **Client:**
  * **Recovery:** Ignore `Default` variants and keep recovering with the ones we understand
  * **Other places:** We only deal with self-generated transactions, panic on `Default`
* If we ever need to change functionality we can add a new `V1` variant in a new minor consensus version (#3571) without breaking old clients

Should I proceed with this approach and introduce it to all modules? @dpc @douglaz @joschisan

### CODE REVIEW

**Review by dpc — APPROVED** [review]
Makes sense to me.

**Comment by douglaz** [comment]
Looks reasonable

**Review by dpc — APPROVED** [review]
:shipit:

**Comment by elsirion** [comment]
@dpc I have two more modules in the pipeline, but if you want we can already merge this first part, I won't get to all the modules today.

**Comment by dpc** [comment]
The faster we land, the merge conflict resolution we need to do.

**Review by dpc — APPROVED** [review]

**Pull request merged**
