### PR TITLE
fix: fix index bug in case of incomplete mid-session recovery

### PR DESCRIPTION
**Pull request by joschisan**

### CODE REVIEW

**Review by elsirion — APPROVED** [review]

**Comment by dpc** [comment]
@joschisan  I am still confused about the

```
let mut item_index = 0;
```

On it's face value, this looks sus. Isn't it possible for this function to be called after a restart on an existing state, where alephbft would start returning following items? Or is it guaranteed to always return all previous items from the current session from index 0 before returning new items?

One way or the other, I think we should add a comment to this variable and explain how it works, and why `= 0` is OK, as it's non-trivial and important to understand the correctness here. Future generations will be thankful.

**Comment by dpc** [comment]
I guess my panic messages / logging PR made this one have a merge conflict now.

**Comment by joschisan** [comment]
> Or is it guaranteed to always return all previous items from the current session from index 0 before returning new items?

It is guaranteed, otherwise there would be no way to assure consistency.

**Review by dpc — APPROVED** [review]

**Comment by fedimint-backports** [comment]
Backport failed for `releases/v0.4`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/v0.4
git worktree add -d .worktree/backport-6166-to-releases/v0.4 origin/releases/v0.4
cd .worktree/backport-6166-to-releases/v0.4
git switch --create backport-6166-to-releases/v0.4
git cherry-pick -x 3b59e19942eb91a153999d6cf00dd7999ac56805
```

**Pull request merged**
