### PR TITLE
fix(cln-extension): avoid holding the sender lock during HTLC processing

### PR DESCRIPTION
**Pull request by douglaz**
On `cln-extension`, while one HTLC was being processed, the `self.sender` lock would be held, blocking further requests to get initiated and making the whole process synchronous.

Also minor code cleanups/improvements.

Closes https://github.com/fedimint/fedimint/issues/3705

### CODE REVIEW

**Review by elsirion — APPROVED** [review]
Great find!

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.2`:
- #3763

**Comment by justinmoon** [comment]
Great PR @douglaz

**Comment by okjodom** [comment]
excellence :) 🔥

**Pull request merged**
