### PR TITLE
test: FederationTestBuilder for building federations in rust tests

### PR DESCRIPTION
**Pull request by m1sterc001guy**
Adds `FederationTestBuilder` which allows us to customize how we build federations in our tests.

### CODE REVIEW

**Comment by dpc** [comment]
> In our rusts tests, we by default run with 1 peer offline to simulate a down peer. However, `FederationTest` allows us to customize how many peers are offline.

Oh. I think we misunderstood each other in Discord.

I wanted to stop injecting extra unreliability when having any peers offline, because it then it affect the performance severely.


Some modules randomly not delivering their CIs is a inherent feature of alephbft. Every module needs to keep proposing the same CI, until it sees it in it's `process_consensus_item`. In a nuthsell. You can check `meta` module for how it keeps track of `desired`.



@m1sterc001guy

**Comment by m1sterc001guy** [comment]
Ok, that's fine, I can refactor it so we don't inject unreliability when there's a peer offline. I would still like the ability to create a reliable federation with all peers online though. I think I'll just make a new function for that.

**Comment by dpc** [comment]
> I would still like the ability to create a reliable federation with all peers online though. I think I'll just make a new function for that.

The whole should be a builder, and test could be able to add `.force_offline_peers(0)` to disable defaults, or something like that.

**Comment by m1sterc001guy** [comment]
Refactored and added `FederationTestBuilder` which allows us to customize how we create test federations. By default, we run with 4 guardians and 1 is offline, with reliable connections. Number of offline peers and reliability of the connections can be customized but none of our tests currently use it.

**Review by dpc — APPROVED** [review]

**Pull request merged**
