### PR TITLE
fix(server): panic when there are no peers

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Review by bradleystachurski — COMMENTED** [review]
Should we also add here?

https://github.com/fedimint/fedimint/blob/5bd29c2d8c49cee33a5c3b9ff4bddcedb1d7eff4/fedimint-server/src/net/peers.rs#L343

**Comment by dpc** [comment]
> Should we also add here?
> 
> https://github.com/fedimint/fedimint/blob/5bd29c2d8c49cee33a5c3b9ff4bddcedb1d7eff4/fedimint-server/src/net/peers.rs#L343

Most certainly. @bradleystachurski . Done.

But ... why do we have such a copypasta here ... ?

**Comment by bradleystachurski** [comment]
> But ... why do we have such a copypasta here ... ?

I was wondering the same thing, but was hoping you had context :smile:

**Comment by dpc** [comment]
> I was wondering the same thing, but was hoping you had context 😄

I'm just the janitor, sir.

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.3`:
- #5191

**Comment by bradleystachurski** [comment]
review club: requires more investigation to know if we can unify the different networking paths

**Pull request merged**
