### PR TITLE
wip: add releases/v0.2 branch to backwards-compatibility matrix

### PR DESCRIPTION
**Pull request by bradleystachurski**
_Do not merge_

Would close https://github.com/fedimint/fedimint/issues/4207

This will give us a matrix that will run
```
0.2.1 <> master
0.2.1 <> HEAD releases/v0.2
HEAD releases/v0.2 <> master
```

We shouldn't merge this PR since we don't need this full version matrix run on each PR. Instead, we can verify locally and using CI for just this PR.

I'm running locally and will upload the result logs when it finishes.

### CODE REVIEW

**Comment by justinmoon** [comment]
When I run this locally on a Mac I get:

```
  = note: ld: framework not found SystemConfiguration
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `fedimint-ldk-node` (lib) due to previous error
```

**Comment by bradleystachurski** [comment]
We're all green 👍 cc: @justinmoon 

```
Backwards-compatibility tests summary:
fed_version    client_version  gateway_version  exit_code
v0.2.1         v0.2.1          releases/v0.2    0
v0.2.1         v0.2.1          current          0
v0.2.1         releases/v0.2   v0.2.1           0
v0.2.1         releases/v0.2   releases/v0.2    0
v0.2.1         releases/v0.2   current          0
v0.2.1         current         v0.2.1           0
v0.2.1         current         releases/v0.2    0
v0.2.1         current         current          0
releases/v0.2  v0.2.1          v0.2.1           0
releases/v0.2  v0.2.1          releases/v0.2    0
releases/v0.2  v0.2.1          current          0
releases/v0.2  releases/v0.2   v0.2.1           0
releases/v0.2  releases/v0.2   current          0
releases/v0.2  current         v0.2.1           0
releases/v0.2  current         releases/v0.2    0
releases/v0.2  current         current          0
current        v0.2.1       v  v0.2.1           0
current        v0.2.1       v  releases/v0.2    0
current        v0.2.1       v  current          0
current        releases/v0.2   v0.2.1           0
current        releases/v0.2   releases/v0.2    0
current        releases/v0.2   current          0
current        current         v0.2.1           0
current        current         releases/v0.2    0
```

**Comment by justinmoon** [comment]
Deleted my previous message (copied into issue https://github.com/fedimint/fedimint/issues/4218) b/c I realized it was operator error. 

https://github.com/fedimint/fedimint/issues/4217 is preventing me from running this, through. And this has happened repeatedly over the past few days.

```
./scripts/tests/backwards-compatibility-test.sh
Running backwards-compatibility tests for versions: v0.2.1 releases/v0.2
Compiling fed binaries for version v0.2.1...
Compiling client binaries for version v0.2.1...
Compiling gateway binaries for version releases/v0.2...
error: builder for '/nix/store/0f3p440vzing4xpdf9j37kq34z110hjz-bitcoind-26.0.drv' failed with exit code 2;
       last 10 log lines:
       >               ^
       > ./support/allocators/pool.h:250:15: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
       > 4 errors generated.
       > make[2]: *** [Makefile:10024: libbitcoin_node_a-blockencodings.o] Error 1
       > 4 errors generated.
       > make[2]: *** [Makefile:10136: libbitcoin_node_a-httprpc.o] Error 1
       > make[2]: Leaving directory '/private/tmp/nix-build-bitcoind-26.0.drv-0/bitcoin-26.0/src'
       > make[1]: *** [Makefile:20138: all-recursive] Error 1
       > make[1]: Leaving directory '/private/tmp/nix-build-bitcoind-26.0.drv-0/bitcoin-26.0/src'
       > make: *** [Makefile:814: all-recursive] Error 1
       For full logs, run 'nix log /nix/store/0f3p440vzing4xpdf9j37kq34z110hjz-bitcoind-26.0.drv'.
error: 1 dependencies of derivation '/nix/store/3x84b0462b01zcw9ziqxrs4rj2r0hamz-gateway-pkgs-group-0.2.2-rc7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y2ib82jscr986j5hijn0yabnk1v5yjs6-gateway-pkgs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s0pqykky2m8z71ilv7gdp0vpcarixj66-gatewayd.drv' failed to build
========== Starting backwards-compatibility run ===========
```

I wonder if backwards compatibility tests should just exit when they encounter a compilation error like this?

**Comment by bradleystachurski** [comment]
> I wonder if backwards compatibility tests should just exit when they encounter a compilation error like this?

Oh interesting, I would have expected the script to exit if there's a failure anywhere outside of the call to `./scripts/tests/test-ci-all.sh`, since that's the only place where we explicitly allow errors.

https://github.com/fedimint/fedimint/blob/e4e0098/scripts/tests/backwards-compatibility-test.sh#L75

What was the behavior? Did the backwards compatibility tests keep running for different versions after the compilation failure?

**Comment by dpc** [comment]
```
All tests successful
========== Finished backwards-compatibility run ===========
fed version: current
client version: current
gateway version: releases/v0.2
Backwards-compatibility tests summary:
fed_version    client_version  gateway_version  exit_code
v0.2.1         v0.2.1          releases/v0.2    0
v0.2.1         v0.2.1          current          0
v0.2.1         releases/v0.2   v0.2.1           0
v0.2.1         releases/v0.2   releases/v0.2    0
v0.2.1         releases/v0.2   current          0
v0.2.1         current         v0.2.1           0
v0.2.1         current         releases/v0.2    0
v0.2.1         current         current          0
releases/v0.2  v0.2.1          v0.2.1           0
releases/v0.2  v0.2.1          releases/v0.2    0
releases/v0.2  v0.2.1          current          0
releases/v0.2  releases/v0.2   v0.2.1           0
releases/v0.2  releases/v0.2   current          0
releases/v0.2  current         v0.2.1           0
releases/v0.2  current         releases/v0.2    0
releases/v0.2  current         current          0
current        v0.2.1          v0.2.1           0
current        v0.2.1          releases/v0.2    0
current        v0.2.1          current          0
current        releases/v0.2   v0.2.1           0
current        releases/v0.2   releases/v0.2    0
current        releases/v0.2   current          0
current        current         v0.2.1           0
current        current         releases/v0.2    0
```

Yo, that took forever.

**Comment by bradleystachurski** [comment]
The previous run I did was vs v0.2.2-rc7. Reran to test v0.2.2-rc8 and we're still good 👍 

```
Backwards-compatibility tests summary:
fed_version    client_version  gateway_version  exit_code
v0.2.1         v0.2.1       v  releases/v0.2    0
v0.2.1         v0.2.1       v  current          0
v0.2.1         releases/v0.2   v0.2.1           0
v0.2.1         releases/v0.2   releases/v0.2    0
v0.2.1         releases/v0.2   current          0
v0.2.1         current         v0.2.1       v   0
v0.2.1         current         releases/v0.2    0
v0.2.1         current         current          0
releases/v0.2  v0.2.1          v0.2.1       v   0
releases/v0.2  v0.2.1          releases/v0.2    0
releases/v0.2  v0.2.1          current          0
releases/v0.2  releases/v0.2   v0.2.1           0
releases/v0.2  releases/v0.2   current          0
releases/v0.2  current         v0.2.1       v   0
releases/v0.2  current         releases/v0.2    0
releases/v0.2  current         current          0
current        v0.2.1       v  v0.2.1       v   0
current        v0.2.1       v  releases/v0.2    0
current        v0.2.1       v  current          0
current        releases/v0.2   v0.2.1           0
current        releases/v0.2   releases/v0.2    0
current        releases/v0.2   current          0
current        current         v0.2.1       v   0
current        current         releases/v0.2    0
```

**Comment by elsirion** [comment]
Let's make this a just command that accepts the versions to test as arguments, so we can run these for the versions we need whenever we want.

**Comment by bradleystachurski** [comment]
Closing since we've cut https://github.com/fedimint/fedimint/releases/tag/v0.2.2

**Pull request closed without merging**
