### PR TITLE
fix: `panic: Must deleted existing spendable note` [broken, don't land]

### LINKED ISSUE #5271: flake: `panic: Must deleted existing spendable note`
```
00:08:31     thread 'tokio-runtime-worker' panicked at modules/fedimint-mint-client/src/lib.rs:1577:10:
00:08:31     Must deleted existing spendable note
00:08:31     stack backtrace:
00:08:31        0: rust_begin_unwind
00:08:31                  at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
00:08:31        1: core::panicking::panic_fmt
00:08:31                  at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
00:08:31        2: core::panicking::panic_display
00:08:31                  at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:196:5
00:08:31        3: core::panicking::panic_str
00:08:31                  at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:171:5
00:08:31        4: core::option::expect_failed
00:08:31                  at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/option.rs:1988:5
00:08:31        5: core::option::Option<T>::expect
00:08:31                  at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/option.rs:894:21
00:08:31        6: {async_fn#0}
00:08:31                  at ./modules/fedimint-mint-client/src/lib.rs:1572:9
00:08:31        7: {async_fn#0}
00:08:31                  at ./modules/fedimint-mint-client/src/lib.rs:1000:80
00:08:31        8: {async_block#0}
00:08:31                  at ./modules/fedimint-mint-client/src/lib.rs:663:56
```

https://github.com/fedimint/fedimint/actions/runs/9041274494/job/24860479614?pr=5259

### PR DESCRIPTION
**Pull request by dpc**
Fix  #5271

In one of the recent commits I've added an assertion to make sure a spendable note was actually always removed when we thought it was, as I was investigating a bug causing notes to be lost (#5195), and it seemed like a good idea.

Too bad it causing flakes now: #5271

So it looks like our reliance on retrying db conflicts (`autocommit`), leads to inability to assert basic expectations about database state, which seems terrible.

In PR I'm adding a little lock to prevent write-write conflicts in this area of the code, and I think it's worthwhile, just to be able to ensure database integrity.

Moreover, I realized that `autocommit` is probably a bad idea altogether.

Application typically require transaction conflict handling, because they are using **shared** databases. But with an embedded databases, there is no sharing with external entities so there *always* should be, or even *must be* a way to structure application and locking to avoid any conflicts, preventing db isolation level issues, inability to assert basic stuff, or just wasting time retrying things.

### CODE REVIEW

**Comment by dpc** [comment]
Damn. This doesn't really work, because what the reading-side sees is being swapped at the moment of commit.

**Comment by maan2003** [comment]
right, locking is better than autocommit. just have a lock for a set of keys.

**Comment by dpc** [comment]
Having to lock more than across the tx commit ruins it though. :(

**Comment by m1sterc001guy** [comment]
Probably not necessary anymore after fixing https://github.com/fedimint/fedimint/issues/5195

**Pull request closed without merging**
