### PR TITLE
Internal routing II

### LINKED ISSUE #461: Gateway should detect internal payments
Currently the Lightning Gateway doesn't recognize when it's paying itself. Unfortunately core-lightning doesn't seem to support self-payments. Thus we should detect these self-payments internally and special-case them (just buy the preimage directly instead of going through CLN).

### PR DESCRIPTION
**Pull request by elsirion**
My take on internal routing. Fixes #461.

### CODE REVIEW

**Review by jkitman — APPROVED** [review]
I think the readability and error-handling is better in this branch.

One question though is whether this is a bug that needs to be fixed https://github.com/fedimint/fedimint/pull/495/files#diff-518eaa39776f4437cb64e868e4a31b14a31449a3e6e864e2e4048b8b8a591454R857

**Comment by okjodom** [comment]
> 
Cross references are broken after a rebase. This bug is tracked by issue #532

**Comment by elsirion** [comment]
As @okjodom mentioned this is a different issue. My commit just doesn't contain the FIXME comment.

Also let me change the commit text, don't want a WIP to potentially get merged.

**Review by okjodom — APPROVED** [review]

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
@elsirion LGTM, should we land? I'm a bit uncler on the FIXME references. There's still one FIXME w.r.t float math rounding in max fee calculation.

**Comment by elsirion** [comment]
Happy to land it, the `FIXME` just stayed in there after some refactoring (that will make it easier to fix eventually, but a fix requires digging into CLN so didn't want to do this here).

**Comment by justinmoon** [comment]
LGTM!

**Pull request merged**
