### PR TITLE
refactor: decompose Nix toolchain code into separate file

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Review by justinmoon — APPROVED** [review]

**Comment by justinmoon** [comment]
Maybe we should have a nix directory eventually for this stuff?

**Review by mxz42 — APPROVED** [review]

**Comment by mxz42** [comment]
> Maybe we should have a nix directory eventually for this stuff?

what do you think @dpc?

**Comment by dpc** [comment]
Yes, but in another PR, as relative paths are going to change and there will be trouble.

**Comment by justinmoon** [comment]
Needs rebase

**Review by mxz42 — APPROVED** [review]

**Review by Maan2003 — APPROVED** [review]

**Pull request merged**
