### PR TITLE
chore: debug flaky sends_ecash_out_of_band_cancel test

### PR DESCRIPTION
**Pull request by dpc**
https://github.com/fedimint/fedimint/actions/runs/8348631889/job/22851011073

I suspect without sleep, 200 retries here might finish really fast.

### CODE REVIEW

**Review by bradleystachurski — COMMENTED** [review]
We're already sleeping, perhaps we should bump from 100 -> 200?

https://github.com/fedimint/fedimint/pull/4625/files#diff-4fe1b9d323a1313b2a615c4939b56de7a50ad1c2ae930f193405b2e75a737b01R252

**Comment by dpc** [comment]
> We're already sleeping, perhaps we should bump from 100 -> 200?

:/

Maybe it was something else then...

**Review by bradleystachurski — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Review by elsirion — APPROVED** [review]
More logging, more good ^^

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.3`:
- #4646

**Pull request merged**
