### PR TITLE
fix: disable flaky test_can_change_routing_fees

### PR DESCRIPTION
**Pull request by dpc**
Re #4300

### CODE REVIEW

**Review by m1sterc001guy — APPROVED** [review]
I'll debug this some today

**Comment by m1sterc001guy** [comment]
Was the issue with this addressed in https://github.com/fedimint/fedimint/pull/4278?

**Comment by dpc** [comment]
This change landed with #4278 , I'm trying https://github.com/fedimint/fedimint/pull/4322 to see if the issue is still there.

**Comment by dpc** [comment]
Still there. See #4350

**Pull request closed without merging**
