### PR TITLE
chore: build with lld on more systems

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Review by elsirion — APPROVED** [review]
Fine by me, if it doesn't work we can always revert. Why didn't we do so in the first place?

**Comment by elsirion** [comment]
Test seems to fail repeatedly.

**Comment by dpc** [comment]
> Fine by me, if it doesn't work we can always revert. Why didn't we do so in the first place?

> Test seems to fail repeatedly.

**Comment by dpc** [comment]
Such a waste of time. :D

**Pull request closed without merging**
