### PR TITLE
Link Gatewayd to UI via API

### LINKED ISSUE #2130: Gateway UI: Gatewayd API Integration
Mintgate defines and uses [mock Gatewayd API](https://github.com/fedimint/fedimint/blob/master/gateway/ui/src/api/Mintgate.mock.ts) which is really nice for development without starting a real Gatewayd instance.

Here is [how it selects an API to use](https://github.com/GETLN/mintgate/blob/main/src/index.tsx#L10:L14) based on environment variable.

We need to plug in to [the real Gatewayd API](https://github.com/fedimint/fedimint/blob/master/gateway/ui/src/index.tsx#L10:L14)

### PR DESCRIPTION
**Pull request by okjodom**
Connect Gateway UI to a gatewayd instance.
Assumes a gatewayd REST api which is the current reality, but we should switch to a JSON RPC API as proposed by #2293

Closes #2130

### CODE REVIEW

**Comment by okjodom** [comment]
@IgboPharaoh you might be interested in this specific work item

**Comment by justinmoon** [comment]
How to test it?

**Comment by okjodom** [comment]
> How to test it?

1. Run tmuxinator with `just tmuxinator`
2. In a `nix develop .#fedimint-ui` shell, `yarn start` to run the gateway ui with the following environment variables:
- `REACT_APP_FM_GATEWAY_API_PASSWORD`
- `REACT_APP_FM_GATEWAY_API_ADDR`

Here is a pre-filled yarn start with a test password to one of the gateways we spin up in tmuxinator

`REACT_APP_FM_GATEWAY_API_PASSWORD="theresnosecondbest" REACT_APP_FM_GATEWAY_API_ADDR="http://127.0.0.1:8175" yarn start`

You should see a live gateway UI connected to gatewayd. Test the functionality, and take note of bugs

**Comment by IgboPharaoh** [comment]
Hello @okjodom I'll like to pick up this issue and work on it. I'm currently looking at the current implementation of the API spec you made in the commits

**Pull request closed without merging**
