### PR TITLE
chore: refactor bitcoinrpc to envs

### PR DESCRIPTION
**Pull request by harsh-ps-2003**
fedimint_core::bitcoinrpc only consists of env stuff, thus better to live under fedimint_core::envs.

`cargo build` was successful after the change.

### CODE REVIEW

**Comment by harsh-ps-2003** [comment]
Intresting CI failure here :
```
Diff in /home/runner/work/fedimint/fedimint/devimint/src/federation.rs at line 8:
 use bitcoincore_rpc::bitcoin::Network;
 use fedimint_core::admin_client::{ConfigGenConnectionsRequest, ConfigGenParamsRequest};
 use fedimint_core::api::{DynGlobalApi, ServerStatus};
-use fedimint_core::envs::BitcoinRpcConfig;
 use fedimint_core::config::{load_from_file, ClientConfig, ServerModuleConfigGenParamsRegistry};
 use fedimint_core::core::LEGACY_HARDCODED_INSTANCE_ID_WALLET;
+use fedimint_core::envs::BitcoinRpcConfig;
 use fedimint_core::module::registry::ModuleDecoderRegistry;
 use fedimint_core::module::{ApiAuth, ModuleCommon};
 use fedimint_core::util::SafeUrl;
 ```

**Comment by dpc** [comment]
Run `just format`

**Comment by harsh-ps-2003** [comment]
Even after formatting 1 error left :
```
Diff in /home/runner/work/fedimint/fedimint/fedimintd/src/fedimintd.rs at line 13:
 };
 use fedimint_core::core::{ModuleInstanceId, ModuleKind};
 use fedimint_core::db::Database;
-use fedimint_core::envs::BitcoinRpcConfig;
-use fedimint_core::envs::{is_env_var_set, FM_USE_UNKNOWN_MODULE_ENV};
+use fedimint_core::envs::{is_env_var_set, BitcoinRpcConfig, FM_USE_UNKNOWN_MODULE_ENV};
 use fedimint_core::module::ServerModuleInit;
 use fedimint_core::task::{sleep, TaskGroup};
 use fedimint_core::timing;
Diff in /home/runner/work/fedimint/fedimint/fedimintd/src/lib.rs at line 5:
     LEGACY_HARDCODED_INSTANCE_ID_LN, LEGACY_HARDCODED_INSTANCE_ID_MINT,
     LEGACY_HARDCODED_INSTANCE_ID_WALLET,
 };
-use fedimint_core::envs::is_env_var_set;
-use fedimint_core::envs::BitcoinRpcConfig;
+use fedimint_core::envs::{is_env_var_set, BitcoinRpcConfig};
 use fedimint_core::module::ServerModuleInit;
 use fedimint_core::util::SafeUrl;
 use fedimint_ln_common::config::{
 ```

**Review by dpc — APPROVED** [review]

**Review by elsirion — APPROVED** [review]
Code looks good, in the future please use `git commit --amend` to edit commits instead of doing minor fixups like formatting in new commits. You might also find `git rebase --interactive` interesting for more advanced history manipulation. Don't feel afraid to force-push to your own branches :)

**Pull request merged**
