### PR TITLE
Rename mechanically minimint into fedimint

### PR DESCRIPTION
**Pull request by dpc**
The core of it is:

```
> git mv minimint-api fedimint-api
> git mv minimint-core fedimint-core
> git mv minimint-derive fedimint-derive
> git mv modules/minimint-ln modules/fedimint-ln
> git mv modules/minimint-mint modules/fedimint-mint
> git mv modules/minimint-wallet modules/fedimint-wallet
> sed -i 's/minimint/fedimint/g' **.rs **.toml .**.yml **.sh **.nix **.md
> sed -i 's/Mini.int/Fedimint/g' **.rs **.toml .**.yml **.sh **.nix **.md
> sed -i 's/MINIMINT/FEDIMINT/g' **.rs **.toml .**.yml **.sh **.nix **.md
> cargo fmt --all
```

\+ some minor fixups.

On top of #425

### CODE REVIEW

**Comment by elsirion** [comment]
The `**` syntax didn't seem to work for me, so I wrote a small `find` script instead:

```bash
  622  find . -not -path './target/*' -not -path './.idea/*' -name '*.rs' -or -name '*.sh' -or -name '*.toml' -or -name '*.yml' -or -name '*.nix' -or -name '*.md' | xargs -I{} sed -i 's/minimint/fedimint/g' {}
  623  find . -not -path './target/*' -not -path './.idea/*' -name '*.rs' -or -name '*.sh' -or -name '*.toml' -or -name '*.yml' -or -name '*.nix' -or -name '*.md' | xargs -I{} sed -i 's/Mini.int/Fedimint/g' {}
  624  find . -not -path './target/*' -not -path './.idea/*' -name '*.rs' -or -name '*.sh' -or -name '*.toml' -or -name '*.yml' -or -name '*.nix' -or -name '*.md' | xargs -I{} sed -i 's/MINIMINT/FEDIMINT/g' {}
```

The output was slightly more extensive than cdc663e7064cbe43c39e4fe5da6e85581ed73369, you can see the [diff here](https://gist.github.com/elsirion/d58de6cd5ce3743dfac6579cd0c6e4b1). I think some of the additional changes are important.

**Comment by dpc** [comment]
@elsirion Thanks. `**` is a fish shell syntax. I think I missed the md files as I was coming up with the exact list, and must have not re-run something. 

Pushed with some extra fixes needed.

**Review by justinmoon — APPROVED** [review]

**Comment by justinmoon** [comment]
Looks good to me. We should also update `Cargo.lock` but that can be a separate commit or PR. Otherwise it will get automatically when anyone tries to run this code after merge.

**Comment by elsirion** [comment]
> We should also update Cargo.lock but that can be a separate commit or PR

That should definitely be part of this PR

**Comment by justinmoon** [comment]
Renamed `Cargo.lock`

**Review by elsirion — APPROVED** [review]
checked against a local version, similar enough results (the diff looks good), LGTM.

**Comment by elsirion** [comment]
MiniMint is dead, long live Fedimint!

**Comment by prusnak** [comment]
branch `master` commit 49de1c7198e9ae23dcd207e0c252868e2676e06c:

```
$ rg -i minimint
Cargo.lock
205:source = "git+https://github.com/fedimint/bitcoin_hashes?branch=minimint#fb2be02f95fac4d21cc8822f4bf63166c7aa8d47"

Cargo.toml
21:bitcoin_hashes = { version = "0.10.0", git = 'https://github.com/fedimint/bitcoin_hashes', branch = 'minimint' }

docs/lifecycle.md
3:* A [`Transaction`](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint-core/src/transaction.rs#L12-L16) Consists of inputs and outputs
27:* [E.g. deposit](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/client/client-lib/src/clients/user.rs#L103-L125)
30:* [Submit transaction](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint/src/consensus/mod.rs#L92), first validation
31:* [Save to DB](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint/src/consensus/mod.rs#L149-L152)
32:* [Generate consensus proposal](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint/src/consensus/mod.rs#L294-L335) with all transactions submitted in the meantime
33:* [Propose to HBBFT](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint/src/lib.rs#L135-L149)
34:* [Process all transactions that were agreed on](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint/src/consensus/mod.rs#L337)
35:* [Each input](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint/src/consensus/mod.rs#L348-L379) and output are processed by its respective module, e.g. for the [Mint module](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/modules/minimint-mint/src/lib.rs#L195-L214)
36:* Some operations need a second round to submit signature shares, they are submitted via [per-module consensus items](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint-api/src/module/mod.rs#L141-L144) (see also [Generate consensus proposal](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint/src/consensus/mod.rs#L294-L335))
37:* These are also [processed by their respective module](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/modules/minimint-mint/src/lib.rs#L120-L135)
40:* [For more details, look at the docs, they are great (at least for modules)!](https://github.com/fedimint/minimint/blob/563c600287decd47e89e15e29ab478648395f378/minimint-api/src/module/mod.rs#L128-L248)
```

**Pull request merged**
