### PR TITLE
Consumer devex improvements [WIP]

### PR DESCRIPTION
**Pull request by litch**
It looks like the distributedgen function being invoked does not tolerate the bitcoinrpc string anymore.

I'll try to make this a nicely packaged PR after I'm more comfortable with how this whole thing starts up, etc.

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Review by elsirion — CHANGES_REQUESTED** [review]
Tested it and it partially works. DJG runs now, but `fedimintd` can't connect to `bitcoind` once started.

When we removed `bitcoind-rpc` as a config field to be given to DKG we added it as an environment variable expected by `fedimintd`. If the variable is not present it will default to `http://127.0.0.1:8332`, which is invalid for regtest. For this to work you need to set `FM_BITCOIND_RPC=http://bitcoind:18443`

**Comment by elsirion** [comment]
Actually, even with my proposed fix it doesn't work for me. Not sure if it's docker weirdness on my end or something more general. You can check with `docker logs --follow fed-server-0-1` if there is connectivity to `bitcoind`. If not the logs will looks as follows:

```
2023-03-22T09:33:57.285659Z  WARN fedimint_bitcoind::bitcoincore_rpc: bitcoind returned error on cmd 'getblockchaininfo': JSON-RPC error: transport error: Didn't receive response data in time, timed out. addr="http://bitcoind:18443"
2023-03-22T09:33:57.285708Z ERROR fedimint_bitcoind::bitcoincore_rpc: error=JSON-RPC error: transport error: Didn't receive response data in time, timed out.
2023-03-22T09:33:57.285720Z  INFO fedimint_bitcoind: Bitcoind error JSON-RPC error: transport error: Didn't receive response data in time, timed out., retrying
```

**Comment by litch** [comment]
Yes I got the error message to move, and was getting a bit of guidance from @dpc on next steps.  I'll make sure it works

**Comment by justinmoon** [comment]
this file has been deleted

**Pull request closed without merging**
