### PR TITLE
Fix CI on master

### PR DESCRIPTION
**Pull request by elsirion**
- [x] Extra docker containers
- [x] Docs

### CODE REVIEW

**Comment by elsirion** [comment]
I can't figure out how to make crane use a nightly toolchain without adding an entirely new version of `craneLib` that overwrites the toolchain, maybe @dpc can shed some light here: 5f865aaa1c6ff135b2e18cccb565de34829dd5e6

**Comment by elsirion** [comment]
Let's at least attempt to fix docker

**Comment by elsirion** [comment]
Thx @dpc for showing me how to build things with nightly in flakebox!

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
BTW. If it was sending notifications to Discord, like `ci-nix.yml` does we would have noticed faster.

**Review by bradleystachurski — APPROVED** [review]
I think we'll also need to update the path for prosody, but we can tackle in a followup.

Closes https://github.com/fedimint/fedimint/issues/4243

**Comment by elsirion** [comment]
> BTW. If it was sending notifications to Discord, like `ci-nix.yml` does we would have noticed faster.

I don't think it's about noticing, it's about getting annoyed enough to fix it :rofl:

**Comment by dpc** [comment]
> I don't think it's about noticing, it's about getting annoyed enough to fix it 🤣

Flakiness has been good enough recently, that I turned on notification on every message in #allerts recently. @elsirion

**Pull request merged**
