### PR TITLE
Make NotEnoughCoins error more desriptive

### PR DESCRIPTION
**Pull request by vnprc**
Rename NotEnoughCoins to InsufficientBalance and include the requested amount and total balance in the error message.

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Review by elsirion — COMMENTED** [review]
Awesome first PR! I left a small rust nit, but looks good to go otherwise :)

**Review by dpc — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Comment by vnprc** [comment]
\o/
first PR merged LFG!

**Comment by dpc** [comment]
Keep it coming. :)

**Comment by justinmoon** [comment]
Nice PR @vnprc!

**Pull request merged**
