### PR TITLE
Optimize ci tests

### PR DESCRIPTION
**Pull request by dpc**
See commit messages.

Before:

Screenshot from 2023-03-08 14-29-59

After:

Screenshot from 2023-03-08 14-29-29

The downside is that we don't get a status-per-test, and instead one step. If it fails one needs to check what failed. (I've put "### Starting ..." that should be easily ctrl+f able to help locate the output of each test)

### CODE REVIEW

**Review by elsirion — APPROVED** [review]

**Review by justinmoon — DISMISSED** [review]

**Review by justinmoon — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Comment by mxz42** [comment]
when I run it locally I get this: 

```sh
(pr/1838 %) | just test-ci-all
./scripts/test-ci-all.sh
### Making sure workspace is built...
[...]
### Starting all tests in parallel...
parallel: invalid option -- '-'
parallel [OPTIONS] command -- arguments
        for each argument, run command with argument, in parallel
parallel [OPTIONS] -- commands
        run specified commands in parallel
error: Recipe `test-ci-all` failed on line 33 with exit code 1
```

**Comment by dpc** [comment]
@mxz42 are you in a `nix develop` shell?

**Comment by dpc** [comment]
Ah, damn. I reproed. On it.

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/pull/1862

**Pull request merged**
