### PR TITLE
fedimint_core::time rework

### PR DESCRIPTION
**Pull request by Maan2003**
this is much easier to use. SystemTime being different types just causes many problems like some trait not being impled on wasm SystemTime (eg: Add, Hash).

A patch to correctly ban `SystemTime::now` will be very helpful. But I couldn't figure out how to write it correctly in semgrep

### CODE REVIEW

**Review by dpc — APPROVED** [review]
LGTM

**Comment by dpc** [comment]
> But I couldn't figure out how to write it correctly in semgrep

@Maan2003 

https://github.com/dpc/fedimint/tree/ban-system-time Please use this, and you'll have to put https://semgrep.dev/docs/ignoring-files-folders-code/#reference-summary `// nosemgrep: rule-id` to whitelist the instance in the `fedimint_core::time` itself.

**Review by elsirion — APPROVED** [review]

**Comment by elsirion** [comment]
> Please cherry-pick [this](https://github.com/dpc/fedimint/commit/a4c1f099e18d3bb9563cec9aeff2dd51ddc52e30), and you'll have to put [`// nosemgrep: rule-id`](https://semgrep.dev/docs/ignoring-files-folders-code/#reference-summary) to whitelist the instance in the `fedimint_core::time` itself.

Not sure if this should be included here, so not merging yet, but feel free to do so yourself @Maan2003.

**Comment by Maan2003** [comment]
> > But I couldn't figure out how to write it correctly in semgrep
> 
> @Maan2003
> 
> Please cherry-pick [this](https://github.com/dpc/fedimint/commit/a4c1f099e18d3bb9563cec9aeff2dd51ddc52e30), and you'll have to put [`// nosemgrep: rule-id`](https://semgrep.dev/docs/ignoring-files-folders-code/#reference-summary) to whitelist the instance in the `fedimint_core::time` itself.

Thanks! I have adjusted it to ban `SystemTime::now` instead.

**Review by dpc — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Pull request merged**
