### PR TITLE
organize fixtures in fedimint-testing crate

### PR DESCRIPTION
**Pull request by NicolaLS**
Developers that use the fedimint crates should be able to test everything like our integration tests. I just moved everything from fixtures in the fedimint-testing crate. 
Made a few fixture struct constructors public and added a default impl because clippy started to complain because of public constructor that has no arguments but no default impl.

### CODE REVIEW

**Comment by NicolaLS** [comment]
just noticed there are a bunch of dependencies that can be removed now from the `integrationtests` crate. Will do that in a rebase if I get a concept ack

**Comment by okjodom** [comment]
> I also wonder whether @okjodom has an opinion for the gateway tests/fixtures.

My preference would be to have shared testing infra & fixtures in `fedimint-testing` then have crate or logical crate group tested in their own scope. An example would be the way `gateway/tests` are structured right now

**Comment by NicolaLS** [comment]
> > I also wonder whether @okjodom has an opinion for the gateway tests/fixtures.
> 
> My preference would be to have shared testing infra & fixtures in `fedimint-testing` then have crate or logical crate group tested in their own scope. An example would be the way `gateway/tests` are structured right now

this works for unit tests but how would you split up integrationtests into multiple crates

**Comment by okjodom** [comment]
> > > I also wonder whether @okjodom has an opinion for the gateway tests/fixtures.
> > 
> > My preference would be to have shared testing infra & fixtures in `fedimint-testing` then have crate or logical crate group tested in their own scope. An example would be the way `gateway/tests` are structured right now
> 
> this works for unit tests but how would you split up integrationtests into multiple crates

I disagree. `gateway/tests` validate integration between gateway components. `gateway/ln-gateway` will contain unit tests

`module/tests` should be integration for that module. Each module might have it's own integration tests if necessary, plus lots of unit tests in the module crate itself

**Comment by jkitman** [comment]
If we want to go with the model of having `fedimint-testing` have all the fixtures and the tests live near the code then we should put `integrationtests/tests.rs` into the `fedimint-server` crate perhaps.

**Comment by okjodom** [comment]
Revisiting the cargo [Package Layout](https://doc.rust-lang.org/cargo/guide/project-layout.html#package-layout) guide. Thought to share because it's relevant here :)

**Comment by NicolaLS** [comment]
> Revisiting the cargo [Package Layout](https://doc.rust-lang.org/cargo/guide/project-layout.html#package-layout) guide. Thought to share because it's relevant here :)

My goal was to add another crate which developers that use any of the other fedimint crates can also pull in as a library to make testing easier. I don't think that this is described in any doc like the cargo package layout because it is more unique/concrete. I'm not sure if this makes sense though and also we probably should reorganize our tests like you suggested @okjodom. I'll close this PR and let's discuss on discord.

**Comment by elsirion** [comment]
> I'll close this PR and let's discuss on discord.

**Pull request closed without merging**
