### PR TITLE
WIP: concurrent integration tests

### PR DESCRIPTION
**Pull request by justinmoon**
This PR generates random ports for server and gateway to bind to. I pulled in a `portpicker` dependency. That project is just [75 LOC](https://github.com/Dentosal/portpicker-rs/blob/master/src/lib.rs) with public domain license, so I think we could just copy any relevant code into our project if this works.

### CODE REVIEW

**Comment by justinmoon** [comment]
CI gets stuck on the `runs_consensus_if_tx_submitted` tests ... will investigate more later

**Comment by justinmoon** [comment]
Eric mentioned alternative fix for making the gateway work in concurrent tests: don't bind to a port. "Interconnect" is able to fake the network layer for our client / server communications in tests. We could do something similar for the gateway.

**Comment by elsirion** [comment]
We could probably re-use the great API @Maan2003 built https://github.com/fedimint/fedimint/blob/2cd4cb8a6dfb70dd3b8f9da1dc16be540489d54f/fedimint-api/src/module/mod.rs#L42-L126

**Comment by justinmoon** [comment]
Closing this. #497 is a better approach.

**Comment by NicolaLS** [comment]
@justinmoon we might still want to switch to portpicker later because we have no gurantee that 4000+((testi_peers*2 + 1)*i) are not used by some other process on the machine

**Comment by justinmoon** [comment]
@NicolaLS Could you try to PR this again? @elsirion was mentioning that he's still getting port-conflicts locally ...

**Comment by elsirion** [comment]
I think I fixed it here: https://github.com/fedimint/fedimint/pull/646/commits/a4f918a0d4baa352a1defc18040b09acdffdc129#diff-48b39828fd7e697f30f09e9a1830b0b515e704bc621c47fdeaa597796a0d0abdR180

**Pull request closed without merging**
