### PR TITLE
Introduce module associated type for backups

### LINKED ISSUE #3654: Make backups typed
Part of #3008 that can be merged independently.

### PR DESCRIPTION
**Pull request by elsirion**
Fixes #3654

* Makes it easier to add versioning to module backups by making them enums
* Probably enables removing `supports_backup` since there's now the `NoBackup` placeholder type (does this sound correct @dpc?)

### CODE REVIEW

**Review by dpc — DISMISSED** [review]

**Comment by dpc** [comment]
This is the way.

**Comment by elsirion** [comment]
Needs more debugging :/ CI still failing

**Comment by dpc** [comment]
We might need to move a static method on that trait  to have some way to know at runtime if backup is actually supported or not (so we can show it to the user, etc.).

**Comment by elsirion** [comment]
I'm pretty sure it isn't a flake given that it happens in the backup test: https://github.com/fedimint/fedimint/actions/runs/6947640396/job/18901870703?pr=3655#step:9:286

**Review by dpc — APPROVED** [review]

**Pull request merged**
