### PR TITLE
Check in daily CI if minimal versions are still compiling

### PR DESCRIPTION
**Pull request by dpc**
This is currently broken, but maybe we can get it to work after updating bitcoin & rand.

### CODE REVIEW

**Comment by elsirion** [comment]
What are the target versions ob `bitcoin` and `rand` for this to work?

**Comment by dpc** [comment]
```
 │   ├── threshold_crypto v0.4.0 (https://github.com/jkitman/threshold_crypto?branch=upgrade-threshold-crypto-libs#a6d60b4f)
│   │   │   ├── bls12_381 v0.7.0
│   │   │   │   ├── ff v0.12.0
│   │   │   │   │   ├── bitvec v1.0.1                            
│   │   │   │   │   │   ├── funty v2.0.0
│   │   │   │   │   │   ├── radium v0.7.0                
│   │   │   │   │   │   ├── tap v1.0.1
│   │   │   │   │   │   └── wyz v0.5.0                           
│   │   │   │   │   │       └── tap v1.0.1
│   │   │   │   │   ├── rand_core v0.6.4 (*)      
│   │   │   │   │   └── subtle v2.4.1       
```

`bitvec 1.0.0` is broken, so `ff` need to specify `1.0.1` dependency.

**Comment by elsirion** [comment]
This should be resolved if #796 is fixed right? Maybe we can just fork `bitvec` for now and repce it workspace-wide in the hope of upstreaming fixs to its dependency mess?

**Comment by dpc** [comment]
> Maybe we can just fork `bitvec` for now and repce it workspace-wide in the hope of upstreaming fixs to its dependency mess?

Seems like quite a bit of work, but yes.

**Pull request closed without merging**
