### PR TITLE
fix: remove unused `Transaction` struct

### PR DESCRIPTION
**Pull request by elsirion**
Was probably an oversight from when I was finishing server modularization.

### CODE REVIEW

**Review by justinmoon — APPROVED** [review]

**Comment by justinmoon** [comment]
doc test failure

**Review by dpc — APPROVED** [review]

**Review by mxz42 — DISMISSED** [review]

**Comment by mxz42** [comment]
doc test fails only because of ```[`Transaction`]``` is not linkable in `core.rs`. 

I think - while on it - you could also update the link in `docs/lifecycle.md` as the link is pinned to a hash.

```sh
pr/1879 %) | rgi '`transaction`'
docs/database.md
81:| OutgoingPaymentClaim    |     `0x24`    | contract id (sha256)               | `Transaction`                |

docs/lifecycle.md
3:- A [`Transaction`](https://github.com/fedimint/fedimint/blob/a1f57e3c6ff860a9c4a998bf88ebad73ebdb67c9/fedimint-core/src/transaction.rs#L12) Consists of inputs and outputs

docs/architecture.md
32:The API task in `net:api:run_server` allows clients to submit a `Transaction` and retrieve the `TransactionStatus`.
48:Any module can contribute inputs and outputs in the same `Transaction`.
63:A submitted `Transaction` often requires multiple epochs to become spendable, usually because they require signatures from a quorum of federation members.

fedimint-core/src/core.rs
361:/// Something that can be an [`DynInput`] in a [`Transaction`]
380:    /// An owned, immutable input to a [`Transaction`]
391:/// Something that can be an [`DynOutput`] in a [`Transaction`]
402:    /// An owned, immutable output of a [`Transaction`]
432:    /// An owned, immutable output of a [`Transaction`] before it was finalized
458:    /// An owned, immutable output of a [`Transaction`] before it was finalized

modules/fedimint-mint-common/src/lib.rs
83:/// [`Note`]s as an `Input`s of `Transaction` with new [`Note`]s being created

```

**Comment by dpc** [comment]
@elsirion let's land (doc link fix needed). Already bit me. :D

**Comment by elsirion** [comment]
> doc test fails only because of `` [`Transaction`] `` is not linkable in `core.rs`.

Fixed with the latest push I think.

> I think - while on it - you could also update the link in `docs/lifecycle.md` as the link is pinned to a hash.

I'll leave it as is, the document assumes a pre-`Dyn*`-type code base, would be very confusing to link to the current one. Eventually we'll need to remove or restructure that document. But it still works well to get the concept across (and then you tell people it's much more complicated in reality :laughing: ).

> @elsirion let's land (doc link fix needed). Already bit me. :D

Given how long nobody noticed I assumed it wasn't as high prion xD

**Review by justinmoon — APPROVED** [review]

**Review by mxz42 — APPROVED** [review]

**Pull request merged**
