### PR TITLE
initialize gateway with different ports

### PR DESCRIPTION
**Pull request by NicolaLS**
Addresses #493 see [comment](https://github.com/fedimint/fedimint/issues/493#issuecomment-1237074302)

### CODE REVIEW

**Comment by NicolaLS** [comment]
mhm running `receive_lightning_payment_valid_preimage` separately succeeds..I'm really confused why CI failed there

**Comment by NicolaLS** [comment]
also code coverage succeeded...

**Comment by NicolaLS** [comment]
I guess it's because of lightningd

**Comment by wilfredallyn** [comment]
I saw another place in the code where `8080` is hardcoded. Does this cause any problems?
https://github.com/fedimint/fedimint/blob/dabd9e46a7049f725b2c26126db01c8e250e54c9/ln-gateway/src/bin/ln_gateway.rs#L194

**Comment by NicolaLS** [comment]
> I saw another place in the code where `8080` is hardcoded. Does this cause any problems?
> 
> https://github.com/fedimint/fedimint/blob/dabd9e46a7049f725b2c26126db01c8e250e54c9/ln-gateway/src/bin/ln_gateway.rs#L194

yeah I think thats a problem :( ty for pointing this out

**Comment by NicolaLS** [comment]
dosn't solve the problem: [see](https://github.com/fedimint/fedimint/issues/493#issuecomment-1237306419)

**Comment by justinmoon** [comment]
> I saw another place in the code where `8080` is hardcoded. Does this cause any problems?
> 
> https://github.com/fedimint/fedimint/blob/dabd9e46a7049f725b2c26126db01c8e250e54c9/ln-gateway/src/bin/ln_gateway.rs#L194

This won't cause problems currently. It's a default port and can be overridden if there is a conflict.

**Comment by justinmoon** [comment]
I think we should just merge this and see if the problem goes away. Seems like a better approach to generate our ports the same way for everything during testing.

**Comment by NicolaLS** [comment]
> I think we should just merge this and see if the problem goes away. Seems like a better approach to generate our ports the same way for everything during testing.

yeah, I think the problem is only on my machine..because I noticed even the server.rs can't bind sometimes

**Comment by NicolaLS** [comment]
@jkitman helped me debug it and I can run the tests on 8 threads with `--release` @justinmoon

**Review by justinmoon — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Pull request merged**
