### PR TITLE
fix: make set_active_gateway concurrency safe

### LINKED ISSUE #4110: set_active_gateway is not concurrency safe
https://github.com/fedimint/fedimint/blob/11339763400401b5394e726b05bf6decc031283e/modules/fedimint-ln-client/src/lib.rs#L866-L888

if called concurrently, second one would panic on database commit

### PR DESCRIPTION
**Pull request by Maan2003**
fixes #4110 

~~just put a lock around it for now~~

return error on concurrent calls

### CODE REVIEW

**Comment by Maan2003** [comment]
i am conflicted with return Error and using lock

error might help you find concurrent calls with set_active_gateway, but lock feels more correct semantically

**Comment by elsirion** [comment]
Why not get rid of `set_active_gateway` altogether?

**Comment by elsirion** [comment]
> i am conflicted with return Error and using lock

Why not auto-commit, if you want to avoid the error case? I don't think it makes sense though, just as the lock version. 

In order of preference:

* Remove the active GW concept
* Fail on concurrent writes
* Autocommit
* Locking

**Comment by Maan2003** [comment]
we still have to keep active gateway in fedimint-cli because of devimint

**Review by elsirion — APPROVED** [review]

**Comment by justinmoon** [comment]
Relevant discussion in https://github.com/fedimint/fedimint/issues/3844

**Review by m1sterc001guy — APPROVED** [review]
Propagating the error up is IMO the best short term solution

**Pull request merged**
