### PR TITLE
fix(devimint): handle generate_to_address failure

### LINKED ISSUE #2805: Problem running mprocs on MacOS x86 architecture
Screenshot 2023-07-20 at 4 36 23 PM
Screenshot 2023-07-20 at 4 36 14 PM

### PR DESCRIPTION
**Pull request by Maan2003**
maybe fixes #2805

### CODE REVIEW

**Comment by otech47** [comment]
Tried running this PR testing `just mprocs` on intel mac (making sure to run `pkill -9 fedimintd lnd lightningd gatewayd devimint esplora electrs bitcoind faucet` first) and I see strange behavior of what seems like blocks being mined on infinite loop

Screenshot 2023-07-24 at 1 38 45 PM

debugging a bit with @Maan2003 we did the following:

1. added debug statements in code (screenshot below)
2. kill mprocs and run `pkill...` command to clean up
3. `cargo build`
4. `export PATH=$PATH:./target/debug`
5. run just the devimint command `devimint --test-dir ./out --fed-size 4 dev-fed` to test

bitcoind seems to get setup in the background and then eventually we see the debug output in the terminal

Screenshot 2023-07-24 at 1 36 27 PM

I also re-ran all of the same debug steps on my M1 Mac off the same PR and everything works completely fine. Works fine on @Maan2003's Linux machine too...

So my takeaway is that `generate_to_address` is running successfully on Intel Mac, but for some reason it is not returning true which is supposed to break the `poll` loop and get the wallet going. The `Resource temporarily unavailable`/`WouldBlock` message is the only clue to go off for now

**Comment by justinmoon** [comment]
@dpc

**Comment by otech47** [comment]
nothing concrete but there might be a lead here?

https://github.com/bitcoin/bitcoin/issues/25724

similar error message... but root cause still not clear

**Comment by dpc** [comment]
Closing due to inactivity. Please reopen if anyone is affected and wants to drive it.

**Pull request closed without merging**
