### PR TITLE
fix: remove leading and trailing newlines from password

### PR DESCRIPTION
**Pull request by dpc**
If the file was created/modified manually, the text editor will likely add an extra newline.

### CODE REVIEW

**Comment by douglaz** [comment]
What if there is actually a space on the password? Perhaps remove only new lines?

**Comment by dpc** [comment]
> What if there is actually a space on the password?

[Illegal](https://www.youtube.com/watch?v=eiyfwZVAzGw).


Note: `trim()` removes only leading and trailing whitespace, so spaces in between are fine.

**Comment by douglaz** [comment]
Spaces are perfectly legal and reasonable in any part of the password. You have no right of enforcing your weak and authoritarian standards on the common people.

**Comment by dpc** [comment]
Not only we have a right, but a moral duty to forbid leading and trailing whitespace in the passwords. *Salus populi suprema lex esto*

Leading and trailing whitespace is a sure way to make sure the user screws up copy&paste, sets a password with characters they are not aware of and then blames us that nothing works.

The passwords that Fedimint IO generates and suggests are 16-character long alpanumerical characters, and our flow heavily suggests copy&paste and backing up the password.

**Comment by IroncladDev** [comment]
image

**Comment by elsirion** [comment]
I wonder if we should at least emit a warning when `trim` did anything. Could be unintuitive to debug otherwise. Or just try the trimmed and the original version when trying to decrypt our secrets to maintain compatibility :laughing: 

Longer term I want to get rid of `password.secret` anyway #6258

**Comment by dpc** [comment]
BTW. I do put spaces in passwords (well, passphrases) in between the words. That's fine. Messing with user passwords is a bad idea. Just the leading and trailing whitespace are 99% user error.

**Comment by dpc** [comment]
OK, so to make it more digestable I changed it to:

* remove online leading/trailing newlines from the existing password
* `warn!` about existing leading/trailing whitespace (other than newlines) in the password file
* reject leading/trailing whitespace on `set_password` api request

**Review by elsirion — APPROVED** [review]

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.4`:
- #6278

**Pull request merged**
