### PR TITLE
feat(tor): put `tor` support behind a feature, use as default

### PR DESCRIPTION
**Pull request by oleonardolima**
related to #4752 

## Description

The usage of `arti-client` for adding Tor support (#5443) recently landed on master, but `arti-client` relies on a bunch of other tor related crates, which can lead to an increase on the binary size.

In order to allow users to have the opt-in/opt-out of such feature and the leading binary increase, this PR adds a new feature where required for Tor support.

## Note for Reviewers

I'm wondering if we should have it by default, as its removal from default-features becomes a SemVer incompatible change.

Any other thoughts on it?

### CODE REVIEW

**Comment by elsirion** [comment]
> I'm wondering if we should have it by default, as its removal from default-features becomes a SemVer incompatible change.

That's ok imo, we still have SemVer breaks regularly and opting out of Tor support should be something very explicit.

**Review by elsirion — APPROVED** [review]
I tested `cargo build -p fedimint-client --no-default-features` and that works. `cargo build --workspace --all-targets --no-default-features` fails to compile the gateway for some reason, but I doubt anyone is explicitly interested in a gateway without tor support.

**Comment by oleonardolima** [comment]
> I tested `cargo build -p fedimint-client --no-default-features` and that works. `cargo build --workspace --all-targets --no-default-features` fails to compile the gateway for some reason, but I doubt anyone is explicitly interested in a gateway without tor support.

It's weird, I'll test it again and take a better look into it. 🤔

**Comment by oleonardolima** [comment]
It fails on the `fedimint-gateway-cli` when running the `cargo build --workspace --all-targets --no-default-features` command, but it works fine when specifically running `cargo build -p fedimint-gateway-cli --no-default-features`.

**Pull request merged**
