### PR TITLE
refactor: split out fedimint-api-client from fedimint-core

### PR DESCRIPTION
**Pull request by dpc**
Only last commit.  On top of (otherwise small but insta-merge-conflict) #4929 

Client API traits and query strategies don't belong to core crate (which almost everything in Fedimint includes).

This should help avoid some rebuilds of some crates, sometimes.

### CODE REVIEW

**Comment by dpc** [comment]
> I think it should be called `fedimint-api-client`. Otherwise someone will get the idea to put stuff in there that should be in `fedimint-client` but "feels `core`".


@elsirion 
Fine with me. Probably more scalable and granular approach anyway.

**Review by maan2003 — DISMISSED** [review]
lets merge it

**Comment by dpc** [comment]
There was a rebase, but a trivial one. There's still a chance. :D

**Review by maan2003 — DISMISSED** [review]

**Review by justinmoon — APPROVED** [review]

**Comment by dpc** [comment]
Some unfortunately silent merge conflict. Rebased, changed the crate name.

**Review by maan2003 — APPROVED** [review]

**Comment by maan2003** [comment]
oh we are already on one review per PR!

**Comment by dpc** [comment]
> oh we are already on one review per PR!

image

@maan2003

**Comment by dpc** [comment]
I can not believe this landed with only one small rebase.

**Pull request merged**
