### PR TITLE
fix: restore in latency tests for 0.2

### PR DESCRIPTION
**Pull request by maan2003**
TODO: how to test this?
given it was not caught in CI

### CODE REVIEW

**Comment by dpc** [comment]
>  given it was not caught in CI

Isn't backward compat running it with old version?

**Comment by Maan2003** [comment]
unsure, but don't see how old code would work on 0.2 client

**Comment by justinmoon** [comment]
dev call: @bradleystachurski needs to update stuff for this to run

**Comment by bradleystachurski** [comment]
If we run latency tests in backwards-compatibility tests with this fix, we'll get the following active state machine error

```
00:08:07 Error: command: /nix/store/fdbrlr3n4n94gs5a1lgnzskhgmv8pimq-fedimint-cli/bin/fedimint-cli --data-dir=/tmp/nix-shell.9B5sqt/devimint-133900/clients/restore-without-backup restore private␣solid␣scan␣forum␣lucky␣security␣million␣tank␣now␣mad␣gasp␣live
00:08:07
00:08:07 Caused by:
00:08:07     exit status: 1
00:08:07     stdout:
00:08:07
00:08:07     stderr:
00:08:07     2024-02-08T22:48:32.309385Z  INFO fedimint_cli::db_locked: Acquiring database lock
00:08:07     2024-02-08T22:48:32.436287Z  INFO fedimint_client::sm::executor: Starting state machine executor task
00:08:07     2024-02-08T22:48:32.436751Z  INFO client::recovery: Restoring from backup
00:08:07     2024-02-08T22:48:32.436829Z  WARN client::recovery: Existing backup not provided. Will attempt to restore from scratch. This might take a long time. id=030754807b4ccd446a4fb577dba7a8218c682c3ee8a66d3ed7458ce0e32d512fd3
00:08:07     2024-02-08T22:48:32.436835Z  INFO client::recovery: Starting recovery from backup for module module_kind=mint module_id=1
00:08:07     2024-02-08T22:48:32.461347Z  WARN client::module::mint: Can not start recovery - existing state machines found
00:08:07     2024-02-08T22:48:32.461388Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
00:08:07     2024-02-08T22:48:32.471238Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
00:08:07     {
00:08:07       "error": "CliError",
00:08:07       "kind": "general_failure",
00:08:07       "message": "failure",
00:08:07       "raw_error": "Found existing active state machines. Mint module recovery must be started on an empty state."
00:08:07     }
```

This TODO comment in cli_tests seems relevant, but I don't have much context.

```
    // TODO: make sure there are no in-progress operations involved
    // This test can't tolerate "spend", but not "reissue"d coins currently,
    // and there's a no clean way to do `reissue` on `spend` output ATM
    // so just putting it here for time being.
```
https://github.com/fedimint/fedimint/blob/a3d82e9/devimint/src/tests.rs#L499-L502

**Comment by dpc** [comment]
@bradleystachurski The recovery test in 0.2 must run on an empty/fresh client db. If we're using any kind of `fork_client` etc. it will not work.

**Comment by dpc** [comment]
@maan2003 @bradleystachurski Month without an update. No stress, just making sure it's not forgotten.

**Comment by bradleystachurski** [comment]
We've introduced restore in latency tests for old clients so we're good to close.

**Pull request closed without merging**
