### PR TITLE
Update advisory-db

### PR DESCRIPTION
**Pull request by dpc**
With:

```
nix flake lock --update-input advisory-db
```

### CODE REVIEW

**Comment by dpc** [comment]
```
       last 10 log lines:
       > Version:       0.1.2
       > Title:         No default limit put on request bodies
       > Date:          2022-08-31
       > ID:            RUSTSEC-2022-0055
       > URL:           https://rustsec.org/advisories/RUSTSEC-2022-0055
       > Solution:      Upgrade to >=0.2.8, <0.3.0-rc.1 OR >=0.3.0-rc.2
       > Dependency tree:
       > axum-core 0.1.2
       >
       > error: 1 vulnerability found!
```

**Comment by elsirion** [comment]
Shouldn't we update this input automatically in CI to see new advisories when they come out?

**Comment by NicolaLS** [comment]
> Shouldn't we update this input automatically in CI to see new advisories when they come out?

Maybe we should do it like #887 ? If we update the advisory db, ci will hold back dev. we cant just let it fail until [this](https://github.com/djc/askama/pull/716) landed..

**Comment by elsirion** [comment]
Yeah, that might even be easier. We can also use a free GH runner for this I assume since we don't need to compile much?

**Comment by elsirion** [comment]
Blocked on a fix for `askama` imo.

**Comment by dpc** [comment]
`askama_axum` got a new version release, but hitting https://github.com/djc/askama/issues/757 now.

**Comment by justinmoon** [comment]
> `askama_axum` got a new version release, but hitting [djc/askama#757](https://github.com/djc/askama/issues/757) now.

Looks like that has been merged & released

**Comment by justinmoon** [comment]
Rebased and it seems to work. Ran the update command and now it warns that `json` is unmaintained, but no errors.

**Review by justinmoon — APPROVED** [review]

**Review by elsirion — APPROVED** [review]

**Pull request merged**
