### PR TITLE
chore(jit-values): return string-copy of the original error

### PR DESCRIPTION
**Pull request by dpc**
Only the first caller to `Jit::get_try` can get the original error, but we can actually return a string-copy of it to other callers, which in most cases should be good enough.

The whole complication here allows retaining the original error (including source chain, backtrace, etc.) which might be useful when using in more concrete use-cases than just starting services in Devimint.

### CODE REVIEW

**Review by maan2003 — APPROVED** [review]

**Comment by maan2003** [comment]
what if return `Arc<anyhow::Error>`, we won't lose anything then

**Comment by maan2003** [comment]
looks std has impl, so it must be a sensible impl
https://doc.rust-lang.org/stable/std/error/trait.Error.html#impl-Error-for-Arc%3CT%3E

**Comment by dpc** [comment]
> what if return `Arc<anyhow::Error>`, we won't lose anything then

Is this even legal?

Try it, if it doesn't require some weird bounds, why not?

**Comment by maan2003** [comment]
:facepalm: anyhow::Error doesn't impl From<Arc<anyhow::Error>>

**Review by elsirion — APPROVED** [review]

**Pull request merged**
