### PR TITLE
chore(deps): bump secp256k1 from 0.24.3 to 0.27.0 for fedimint-testing

### PR DESCRIPTION
**Pull request by tvolk131**
Part of #2356

### CODE REVIEW

**Review by elsirion — DISMISSED** [review]

**Comment by tvolk131** [comment]
Sorry, I accidentally rebased!

**Review by dpc — APPROVED** [review]

**Comment by elsirion** [comment]
Also needs a rebase

**Comment by tvolk131** [comment]
> Also needs a rebase

Done! Looks like a compatibility test is failing due to routing fees being different in fedimintd v0.2.1 vs v0.3.0, but the test is passing in #4861 which is stacked on top of this, so I'm guessing it's a flake but I'm not sure how to trigger a re-run.

**Comment by elsirion** [comment]
> > Also needs a rebase
> 
> Done! Looks like a compatibility test is failing due to routing fees being different in fedimintd v0.2.1 vs v0.3.0, but the test is passing in #4861 which is stacked on top of this, so I'm guessing it's a flake but I'm not sure how to trigger a re-run.

I see, but why would it only happen here? @m1sterc001guy @bradleystachurski 

Screenshot 2024-04-12 at 14-59-41 Untitled diff - Diffchecker

**Comment by bradleystachurski** [comment]
I'm having trouble finding the logs that show a back-compat failure due to routing fess. Does anyone happen to have a link?

I've run locally and can't reproduce so I'd assume this is a flake. If I see a similar failure in CI (or if anyone has a link to the referenced failure) I'll create an issue to track.

**Comment by bradleystachurski** [comment]
Just bumped into a similar flake and created an issue https://github.com/fedimint/fedimint/issues/4988

**Pull request merged**
