### PR TITLE
fix: avoid warnings on recovery from mid session crash

### PR DESCRIPTION
**Pull request by joschisan**

### CODE REVIEW

**Review by elsirion — APPROVED** [review]
I think this approach works well for this particular case but should otherwise be discouraged. What do you think @dpc? The alternative would be disabling the warning also on the other early return, which would be more standard.

**Comment by elsirion** [comment]
Waiting for DPC ;)

**Comment by dpc** [comment]
LGTM. The less mutation, the better, but whatever is simpler works, and it's all just diagnostics anyway.

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.2`:
- #3778

**Pull request merged**
