### PR TITLE
fix: in scripts use `set -euo`, not `set -euox`

### PR DESCRIPTION
**Pull request by dpc**
`set -x` produces waay too much output.

### CODE REVIEW

**Comment by dpc** [comment]
@justinmoon :+1: / :-1: :question:

**Comment by elsirion** [comment]
I really like knowing which command produced which output, maybe we can [make it optional and only activate it in debug mode](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging)?

**Comment by dpc** [comment]
> I really like knowing which command produced which output

For the scripts itself? `-x` prints lots of extra stuff. Every `lightning-cli`, `bitcoin-cli`, etc., the responses from (long jsons) etc.

Anyway - if we want it, we can keep them. I don't think we did `-x` everywhere previously, so I thought introducing it in all script was a mistake.

`ACTIONS_STEP_DEBUG` seems like debugging the github action runner itself.

**Comment by elsirion** [comment]
> `ACTIONS_STEP_DEBUG` seems like debugging the github action runner itself.

Maybe I got that wrong, when you re-run GH actions allows to re-run ind debug mode, I thought we could read that env var and activate the extended logging with that.

> I don't think we did `-x` everywhere previously, so I thought introducing it in all script was a mistake.

We did have it everywhere in the beginning (I often include it in my scripts to know what's going on), maybe it was removed in the meantime and now re-introduced? Anyway, we can remove it if you want (at least we come across a bug where nobody knows where a log line might have come from and we re-introduce it :stuck_out_tongue:).

**Review by elsirion — APPROVED** [review]

**Review by jkitman — APPROVED** [review]
I also use it for debugging the tests often, but it's easy enough to add back I suppose.

**Comment by dpc** [comment]
> I also use it for debugging the tests often, but it's easy enough to add back I suppose.

Yeah. The question is - do you want to see it every time, or are you OK adding `x` manually when you are debugging the bash scripts itself.

**Pull request merged**
