### PR TITLE
 chore: fix code coverage status symbols 

### PR DESCRIPTION
**Pull request by dpc**
https://docs.codecov.com/docs/commit-status#target

Fix https://github.com/fedimint/fedimint/issues/2105

### CODE REVIEW

**Review by elsirion — APPROVED** [review]
Let's give this a try.

TIL: one can validate the `codecov.yml` syntax using an API endpoint:

```
curl -X POST --data-binary @.codecov.yml https://codecov.io/validate
```

**Comment by justinmoon** [comment]
> 

> Let's give this a try.
> 
> TIL: one can validate the `codecov.yml` syntax using an API endpoint:
> 
> ```
> curl -X POST --data-binary @.codecov.yml https://codecov.io/validate
> ```

We should almost have CI check this. Believe we've had improperly formatted codecov.yml in the past and didn't even know.

**Comment by dpc** [comment]
Like this one? https://github.com/fedimint/fedimint/blob/3be84d4650f8f829889ec6b6a3d2fd22cf5727f4/.github/workflows/ci-nix.yml#L136

**Comment by justinmoon** [comment]
https://tenor.com/view/ace-ventura-jim-carrey-hes-good-could-be-with-my-help-the-best-gif-15577417

**Pull request merged**
