### PR TITLE
#4935 issue : Remove validator dependency 

### PR DESCRIPTION
**Pull request by Minimega12121**
replaced fn validate_peg_in_proof  to impl fn validate to remove 'validator' dependency

### CODE REVIEW

**Comment by dpc** [comment]
Please rebase, squash and clean up the PR description. :+1:

**Review by tvolk131 — CHANGES_REQUESTED** [review]

**Comment by tvolk131** [comment]
LGTM other than what dpc mentioned and a few nitpicks in the code

**Review by tvolk131 — APPROVED** [review]

**Comment by dpc** [comment]
Please don't use `git merge`, and `git rebase` your changes on top of `master` branch.

https://www.freecodecamp.org/news/how-to-use-git-rebase/

**Review by maan2003 — CHANGES_REQUESTED** [review]
doesn't validate in serde::Deserialize impl

**Pull request closed without merging**
