### PR TITLE
cleanup: rename public_key to module_public_key

### PR DESCRIPTION
**Pull request by joschisan**

### CODE REVIEW

**Comment by elsirion** [comment]
I don't see how this makes things more clear, from the user client's PoV the public key belonging to the gateway's LN module is an implementation detail. Maybe we can find a better description? Or just document what it's used for?

**Comment by joschisan** [comment]
@elsirion Well its better then just public_key. I could not come up with a better name; I am aware its an implementation detail but when you are familiar with lnv2 it makes sense.

**Comment by elsirion** [comment]
If there is no more self-descriptive name, can you please at least add some docs to the field? What is it used for?

**Comment by joschisan** [comment]
@elsirion added documentation to all fields.

**Review by elsirion — APPROVED** [review]

**Pull request merged**
