### PR TITLE
fix: don't config gen in run-ui

### PR DESCRIPTION
**Pull request by Maan2003**

### CODE REVIEW

**Comment by justinmoon** [comment]
Pushed a commit setting the metrics port. Also changed it to start from 3510 instead of 3000 (which was used by fedimint/ui).

**Comment by elsirion** [comment]
Is there any blocker apart from CI?

**Comment by justinmoon** [comment]
> Is there any blocker apart from CI?

I don't think so. Might want to rename this command. It used to actually run the UI server, but that doesn't exist anymore. Might rename to something like `dev-fed-no-dkg` or something.

**Comment by Maan2003** [comment]
what about `devimint fed-setup`

**Review by justinmoon — APPROVED** [review]

**Pull request merged**
