### PR TITLE
chore: fix nightly clippy warnings

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Comment by bradleystachurski** [comment]
How are you triggering nightly clippy here? I pulled this branch, `git reset --hard HEAD~1`, and clippy didn't find any errors.

**Comment by bradleystachurski** [comment]
Ahh, looks like you're updating the toolchain and fixing in a separate PR, then porting the fixes here.

[`d66c68f` (#4498)](https://github.com/fedimint/fedimint/pull/4498/commits/d66c68f708798a6f8269f476a93aeebf013cde6b)

**Review by bradleystachurski — APPROVED** [review]
Verified nightly clippy errors without these fixes using `flake.nix` applied in [`0827c01` (#4498)](https://github.com/fedimint/fedimint/pull/4498/commits/0827c019184c1440953644e2af469ef260b11d9e)

`.truncate` is a good clippy warning, everywhere it's true here makes sense 👍

**Comment by Kodylow** [comment]
tACK, nightly clippy passing with no warnings, only warnings I get are these 2 in `test` but think those are separate:

```
warning: use of deprecated tuple variant `transaction::sm::TxSubmissionStates::NonRetryableError`: all errors should be retried
  --> fedimint-client/src/transaction/sm.rs:93:33
   |
93 | ...nStates::NonRetryableError(..) => {
   |             ^^^^^^^^^^^^^^^^^

warning: `fedimint-client` (lib) generated 3 warnings
warning: use of deprecated method `miniscript::Descriptor::<Pk>::max_satisfaction_weight`: use max_weight_to_satisfy instead
    --> modules/fedimint-wallet-server/src/lib.rs:1352:14
     |
1352 |             .max_satisfaction_weight()
```

**Review by Kodylow — APPROVED** [review]
tACK

**Review by elsirion — APPROVED** [review]
Good clippy warnings!

**Comment by dpc** [comment]
Failed due to ccov run timeout . Maybe #4502 is needed.

**Comment by dpc** [comment]
Actually, probably nothing will pass until https://github.com/fedimint/fedimint/pull/4503 is there.

**Pull request merged**
