### PR TITLE
fix: remove racy endpoint PENDING_ACCEPTED_ITEMS_ENDPOINT for SESSION_STATUS_ENDPOINT

### PR DESCRIPTION
**Pull request by joschisan**

### CODE REVIEW

**Review by dpc — COMMENTED** [review]
Generally fine with me and better than before, but one problem with this is that the result can't be cached.

If the response included some flag if this session is closed or not the it could (when closed).

**Review by dpc — DISMISSED** [review]
:heart:

**Comment by elsirion** [comment]
Do we actually need to cache this? I'd imagine to only use this endpoint for the last session we want to fetch. I think that's lower complexity overall than trying to adapt the cache to potentially non-final responses.

**Review by elsirion — DISMISSED** [review]
LGTM

**Comment by elsirion** [comment]
Also needs backporting since the previous version was backported too #4134 and we don't want two different APIs to live on in the next release.

@dpc don't we also have to bump the minor API version here?

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
> @dpc don't we also have to bump the minor API version here?

Right.

**Review by dpc — APPROVED** [review]

**Comment by fedimint-backports** [comment]
Successfully created backport PR for `releases/v0.2`:
- #4180

**Comment by elsirion** [comment]
I get the feeling we should also document when an API was introduced and enforce that via CI somehow. Otherwise it will be fairly hard to figure out later on.

**Comment by dpc** [comment]
> I get the feeling we should also document when an API was introduced and enforce that via CI somehow.

Semgrep rule to put a specially formatted comment on every api_endpoint!?

Or maybe just an extra argument to the macro...

**Pull request merged**
