### PR TITLE
 feat: make user code put ClientHandle in Arc 

### PR DESCRIPTION
**Pull request by maan2003**
gives more control to user code

on top of #4535

### CODE REVIEW

**Comment by dpc** [comment]
Interesting. Maybe you're right.

**Comment by maan2003** [comment]
with this maybe restart can be `pub async fn restart(&mut self) -> ()`

and never fail because you have unique `ClientHandle`

**Comment by maan2003** [comment]
someone can use `Arc<RwLock<ClientHandle>>` so restarts are always possible

**Comment by dpc** [comment]
> someone can use `Arc<RwLock<ClientHandle>>` so restarts are always possible

I think I just posted basically same/matching conclusion in the other place we talk. :D

:+1: Go for it. :)

**Review by dpc — DISMISSED** [review]

**Review by justinmoon — APPROVED** [review]

**Comment by maan2003** [comment]
rebased

**Review by bradleystachurski — DISMISSED** [review]

**Review by dpc — APPROVED** [review]

**Comment by maan2003** [comment]
rebased again

**Review by dpc — DISMISSED** [review]

**Review by justinmoon — APPROVED** [review]

**Review by dpc — APPROVED** [review]

**Review by justinmoon — APPROVED** [review]

**Pull request merged**
