### PR TITLE
chore: remove unused dependency features from fedimint-core

### PR DESCRIPTION
**Pull request by tvolk131**

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
Merge conflict, oof.

**Comment by tvolk131** [comment]
Oooh, so close!

Rebased

**Review by dpc — DISMISSED** [review]

**Comment by dpc** [comment]
wasm broken

**Review by dpc — APPROVED** [review]

**Comment by elsirion** [comment]
> @tvolk131 Ping me directly on Discord if you ever need it quickly approved, so we can get it through somehow. :D

Same. (currently WASM is still broken though)

**Review by dpc — DISMISSED** [review]

**Comment by elsirion** [comment]
Cross-compiling is failing.

**Comment by dpc** [comment]
`serde` feature on `url` somewhere missing

**Review by dpc — DISMISSED** [review]

**Review by dpc — APPROVED** [review]

**Comment by elsirion** [comment]
I pushed a suspected fix for the CI failure, feel free to squash/delete if it works/doesn't.

**Comment by dpc** [comment]
image

**Comment by dpc** [comment]
Wasm xcompile failing.

**Comment by tvolk131** [comment]
Too much work, not worth the effort 🤦

**Pull request closed without merging**
