### PR TITLE
chore(test): more logging to debug #5163

### PR DESCRIPTION
**Pull request by elsirion**

### CODE REVIEW

**Review by dpc — DISMISSED** [review]

**Comment by dpc** [comment]
@elsirion compilation error, needs a `+ '_`

**Comment by elsirion** [comment]
> @elsirion compilation error, needs a `+ '_`

Yeah, just saw it, I wonder why local clippy didn't complain. Maybe I need to refresh my dev env? Haven't restarted it in a few days.

**Comment by dpc** [comment]
RA using clippy might be your local setting @elsirion 

E.g. from my `~/.config/helix/languages.toml`

```
[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

checkOnSave.command = "clippy"
```

**Comment by elsirion** [comment]
I'm just using the `just clippy` command right now since my IDE setup is kinda broken again :sweat_smile: but maybe it's using weird versions or something since I'm running it in the IDE shell.

**Pull request merged**
