### PR TITLE
fix: semgrep not available on Aarch64 MacOS

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Review by elsirion — DISMISSED** [review]

**Comment by elsirion** [comment]
Why merge master into this branch?

**Comment by dpc** [comment]
No idea how this happened...

**Comment by dpc** [comment]
Oh. I've pushed the update in the UI. I see. We should maybe remove the "merge" option. We never want to use it, as we don't seem to care about preserving the signed commits or anything like that.

**Review by elsirion — APPROVED** [review]

**Review by oleonardolima — APPROVED** [review]
`direnv allow` and `nix develop` now works for me with no semgrep errors (on aarch64-apple-darwin) :shipit:

**Review by oleonardolima — DISMISSED** [review]

**Review by elsirion — APPROVED** [review]

**Review by jkitman — APPROVED** [review]

**Pull request merged**
