### PR TITLE
chore: `nix flake update`

### PR DESCRIPTION
**Pull request by justinmoon**
Should fix CI for https://github.com/fedimint/fedimint/pull/3997 and https://github.com/fedimint/fedimint/pull/3994

### CODE REVIEW

**Comment by justinmoon** [comment]
Didn't work. Could use some help here @dpc.

**Comment by justinmoon** [comment]
`nix flake lock --update-input flakebox/nixpkg` fixed it. Thanks @Maan2003!

**Review by elsirion — APPROVED** [review]

**Review by Maan2003 — APPROVED** [review]

**Review by okjodom — APPROVED** [review]

**Comment by benthecarman** [comment]
Looks like merge for this failed

**Comment by okjodom** [comment]
Re-added to the merge queue but this [failed run on macos](https://github.com/fedimint/fedimint/actions/runs/7400054843/job/20132861506) looks very suspect. Did it fail because of the skipped stages?

**Comment by justinmoon** [comment]
> Looks like merge for this failed

IIRC the MacOS job isn't required because it can be slow. Is that right @dpc?

**Comment by justinmoon** [comment]
Note: when I updated it re-compiled bitcoind when running `nix develop`. IIRC we didn't have to manually re-compile bitcoind in the past. Seems like we should be able to just get a bitcoind binary. Perhaps this only happens in MacOS.

**Pull request merged**
