### PR TITLE
feat(nix): build and publish `fedimint-devtools` container

### PR DESCRIPTION
**Pull request by dpc**
Use `nix build -L .#container.fedimint-devtools` to build locally.

### CODE REVIEW

**Comment by dpc** [comment]
@elsirion Are you able to create thew new dockerhub repo?

**Comment by elsirion** [comment]
Not that I'm aware of. I do have a docker hub account but it appears to have no rights. It's likely that the fedimint namespace is a normal user account someone created because there were some pricing shenanigans for organizations …

**Comment by dpc** [comment]
@justinmoon I bet it was you.

**Comment by elsirion** [comment]
We have [`fedimint/devtools`](https://hub.docker.com/r/fedimint/devtools) now since `fedimint/fedimint-devtools` seemed a bit redundant.

**Comment by justinmoon** [comment]
> We have [fedimint/devtools](https://hub.docker.com/r/fedimint/devtools) now since fedimint/fedimint-devtools seemed a bit redundant.

So let's rename `fedimint/fedimint-devtools` to `fedimint/devtools` in the code here.

**Review by elsirion — APPROVED** [review]

**Pull request merged**
